package cn.caecc.erp.modules.dao.mybatis.mapper;

import cn.caecc.erp.modules.dao.mybatis.entity.UserRoleRelationshipExample;
import cn.caecc.erp.modules.dao.mybatis.entity.UserRoleRelationshipKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserRoleRelationshipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_relationship
     *
     * @mbggenerated Thu Jun 14 15:43:41 CST 2018
     */
    int countByExample(UserRoleRelationshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_relationship
     *
     * @mbggenerated Thu Jun 14 15:43:41 CST 2018
     */
    int deleteByExample(UserRoleRelationshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_relationship
     *
     * @mbggenerated Thu Jun 14 15:43:41 CST 2018
     */
    int deleteByPrimaryKey(UserRoleRelationshipKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_relationship
     *
     * @mbggenerated Thu Jun 14 15:43:41 CST 2018
     */
    int insert(UserRoleRelationshipKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_relationship
     *
     * @mbggenerated Thu Jun 14 15:43:41 CST 2018
     */
    int insertSelective(UserRoleRelationshipKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_relationship
     *
     * @mbggenerated Thu Jun 14 15:43:41 CST 2018
     */
    List<UserRoleRelationshipKey> selectByExample(UserRoleRelationshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_relationship
     *
     * @mbggenerated Thu Jun 14 15:43:41 CST 2018
     */
    int updateByExampleSelective(@Param("record") UserRoleRelationshipKey record, @Param("example") UserRoleRelationshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_relationship
     *
     * @mbggenerated Thu Jun 14 15:43:41 CST 2018
     */
    int updateByExample(@Param("record") UserRoleRelationshipKey record, @Param("example") UserRoleRelationshipExample example);
}