package cn.caecc.erp.modules.dao.mybatis.mapper;

import cn.caecc.erp.modules.dao.mybatis.entity.MessageType;
import cn.caecc.erp.modules.dao.mybatis.entity.MessageTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MessageTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_type
     *
     * @mbggenerated Sat Aug 04 17:33:02 CST 2018
     */
    int countByExample(MessageTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_type
     *
     * @mbggenerated Sat Aug 04 17:33:02 CST 2018
     */
    int deleteByExample(MessageTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_type
     *
     * @mbggenerated Sat Aug 04 17:33:02 CST 2018
     */
    int deleteByPrimaryKey(Integer messagetypeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_type
     *
     * @mbggenerated Sat Aug 04 17:33:02 CST 2018
     */
    int insert(MessageType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_type
     *
     * @mbggenerated Sat Aug 04 17:33:02 CST 2018
     */
    int insertSelective(MessageType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_type
     *
     * @mbggenerated Sat Aug 04 17:33:02 CST 2018
     */
    List<MessageType> selectByExample(MessageTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_type
     *
     * @mbggenerated Sat Aug 04 17:33:02 CST 2018
     */
    MessageType selectByPrimaryKey(Integer messagetypeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_type
     *
     * @mbggenerated Sat Aug 04 17:33:02 CST 2018
     */
    int updateByExampleSelective(@Param("record") MessageType record, @Param("example") MessageTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_type
     *
     * @mbggenerated Sat Aug 04 17:33:02 CST 2018
     */
    int updateByExample(@Param("record") MessageType record, @Param("example") MessageTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_type
     *
     * @mbggenerated Sat Aug 04 17:33:02 CST 2018
     */
    int updateByPrimaryKeySelective(MessageType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_type
     *
     * @mbggenerated Sat Aug 04 17:33:02 CST 2018
     */
    int updateByPrimaryKey(MessageType record);
}