package cn.caecc.erp.modules.dao.mybatis.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class WellXwDailyExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table well_xw_daily
     *
     * @mbggenerated Tue Jun 26 17:52:59 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table well_xw_daily
     *
     * @mbggenerated Tue Jun 26 17:52:59 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table well_xw_daily
     *
     * @mbggenerated Tue Jun 26 17:52:59 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_xw_daily
     *
     * @mbggenerated Tue Jun 26 17:52:59 CST 2018
     */
    public WellXwDailyExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_xw_daily
     *
     * @mbggenerated Tue Jun 26 17:52:59 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_xw_daily
     *
     * @mbggenerated Tue Jun 26 17:52:59 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_xw_daily
     *
     * @mbggenerated Tue Jun 26 17:52:59 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_xw_daily
     *
     * @mbggenerated Tue Jun 26 17:52:59 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_xw_daily
     *
     * @mbggenerated Tue Jun 26 17:52:59 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_xw_daily
     *
     * @mbggenerated Tue Jun 26 17:52:59 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_xw_daily
     *
     * @mbggenerated Tue Jun 26 17:52:59 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_xw_daily
     *
     * @mbggenerated Tue Jun 26 17:52:59 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_xw_daily
     *
     * @mbggenerated Tue Jun 26 17:52:59 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_xw_daily
     *
     * @mbggenerated Tue Jun 26 17:52:59 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table well_xw_daily
     *
     * @mbggenerated Tue Jun 26 17:52:59 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("Id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("Id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("Id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("Id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("Id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("Id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("Id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("Id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("Id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("Id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("Id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("Id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andLogdateIsNull() {
            addCriterion("LogDate is null");
            return (Criteria) this;
        }

        public Criteria andLogdateIsNotNull() {
            addCriterion("LogDate is not null");
            return (Criteria) this;
        }

        public Criteria andLogdateEqualTo(Date value) {
            addCriterionForJDBCDate("LogDate =", value, "logdate");
            return (Criteria) this;
        }

        public Criteria andLogdateNotEqualTo(Date value) {
            addCriterionForJDBCDate("LogDate <>", value, "logdate");
            return (Criteria) this;
        }

        public Criteria andLogdateGreaterThan(Date value) {
            addCriterionForJDBCDate("LogDate >", value, "logdate");
            return (Criteria) this;
        }

        public Criteria andLogdateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("LogDate >=", value, "logdate");
            return (Criteria) this;
        }

        public Criteria andLogdateLessThan(Date value) {
            addCriterionForJDBCDate("LogDate <", value, "logdate");
            return (Criteria) this;
        }

        public Criteria andLogdateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("LogDate <=", value, "logdate");
            return (Criteria) this;
        }

        public Criteria andLogdateIn(List<Date> values) {
            addCriterionForJDBCDate("LogDate in", values, "logdate");
            return (Criteria) this;
        }

        public Criteria andLogdateNotIn(List<Date> values) {
            addCriterionForJDBCDate("LogDate not in", values, "logdate");
            return (Criteria) this;
        }

        public Criteria andLogdateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("LogDate between", value1, value2, "logdate");
            return (Criteria) this;
        }

        public Criteria andLogdateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("LogDate not between", value1, value2, "logdate");
            return (Criteria) this;
        }

        public Criteria andDidIsNull() {
            addCriterion("Did is null");
            return (Criteria) this;
        }

        public Criteria andDidIsNotNull() {
            addCriterion("Did is not null");
            return (Criteria) this;
        }

        public Criteria andDidEqualTo(Integer value) {
            addCriterion("Did =", value, "did");
            return (Criteria) this;
        }

        public Criteria andDidNotEqualTo(Integer value) {
            addCriterion("Did <>", value, "did");
            return (Criteria) this;
        }

        public Criteria andDidGreaterThan(Integer value) {
            addCriterion("Did >", value, "did");
            return (Criteria) this;
        }

        public Criteria andDidGreaterThanOrEqualTo(Integer value) {
            addCriterion("Did >=", value, "did");
            return (Criteria) this;
        }

        public Criteria andDidLessThan(Integer value) {
            addCriterion("Did <", value, "did");
            return (Criteria) this;
        }

        public Criteria andDidLessThanOrEqualTo(Integer value) {
            addCriterion("Did <=", value, "did");
            return (Criteria) this;
        }

        public Criteria andDidIn(List<Integer> values) {
            addCriterion("Did in", values, "did");
            return (Criteria) this;
        }

        public Criteria andDidNotIn(List<Integer> values) {
            addCriterion("Did not in", values, "did");
            return (Criteria) this;
        }

        public Criteria andDidBetween(Integer value1, Integer value2) {
            addCriterion("Did between", value1, value2, "did");
            return (Criteria) this;
        }

        public Criteria andDidNotBetween(Integer value1, Integer value2) {
            addCriterion("Did not between", value1, value2, "did");
            return (Criteria) this;
        }

        public Criteria andWellidIsNull() {
            addCriterion("WellId is null");
            return (Criteria) this;
        }

        public Criteria andWellidIsNotNull() {
            addCriterion("WellId is not null");
            return (Criteria) this;
        }

        public Criteria andWellidEqualTo(Integer value) {
            addCriterion("WellId =", value, "wellid");
            return (Criteria) this;
        }

        public Criteria andWellidNotEqualTo(Integer value) {
            addCriterion("WellId <>", value, "wellid");
            return (Criteria) this;
        }

        public Criteria andWellidGreaterThan(Integer value) {
            addCriterion("WellId >", value, "wellid");
            return (Criteria) this;
        }

        public Criteria andWellidGreaterThanOrEqualTo(Integer value) {
            addCriterion("WellId >=", value, "wellid");
            return (Criteria) this;
        }

        public Criteria andWellidLessThan(Integer value) {
            addCriterion("WellId <", value, "wellid");
            return (Criteria) this;
        }

        public Criteria andWellidLessThanOrEqualTo(Integer value) {
            addCriterion("WellId <=", value, "wellid");
            return (Criteria) this;
        }

        public Criteria andWellidIn(List<Integer> values) {
            addCriterion("WellId in", values, "wellid");
            return (Criteria) this;
        }

        public Criteria andWellidNotIn(List<Integer> values) {
            addCriterion("WellId not in", values, "wellid");
            return (Criteria) this;
        }

        public Criteria andWellidBetween(Integer value1, Integer value2) {
            addCriterion("WellId between", value1, value2, "wellid");
            return (Criteria) this;
        }

        public Criteria andWellidNotBetween(Integer value1, Integer value2) {
            addCriterion("WellId not between", value1, value2, "wellid");
            return (Criteria) this;
        }

        public Criteria andTdepthIsNull() {
            addCriterion("TDepth is null");
            return (Criteria) this;
        }

        public Criteria andTdepthIsNotNull() {
            addCriterion("TDepth is not null");
            return (Criteria) this;
        }

        public Criteria andTdepthEqualTo(Double value) {
            addCriterion("TDepth =", value, "tdepth");
            return (Criteria) this;
        }

        public Criteria andTdepthNotEqualTo(Double value) {
            addCriterion("TDepth <>", value, "tdepth");
            return (Criteria) this;
        }

        public Criteria andTdepthGreaterThan(Double value) {
            addCriterion("TDepth >", value, "tdepth");
            return (Criteria) this;
        }

        public Criteria andTdepthGreaterThanOrEqualTo(Double value) {
            addCriterion("TDepth >=", value, "tdepth");
            return (Criteria) this;
        }

        public Criteria andTdepthLessThan(Double value) {
            addCriterion("TDepth <", value, "tdepth");
            return (Criteria) this;
        }

        public Criteria andTdepthLessThanOrEqualTo(Double value) {
            addCriterion("TDepth <=", value, "tdepth");
            return (Criteria) this;
        }

        public Criteria andTdepthIn(List<Double> values) {
            addCriterion("TDepth in", values, "tdepth");
            return (Criteria) this;
        }

        public Criteria andTdepthNotIn(List<Double> values) {
            addCriterion("TDepth not in", values, "tdepth");
            return (Criteria) this;
        }

        public Criteria andTdepthBetween(Double value1, Double value2) {
            addCriterion("TDepth between", value1, value2, "tdepth");
            return (Criteria) this;
        }

        public Criteria andTdepthNotBetween(Double value1, Double value2) {
            addCriterion("TDepth not between", value1, value2, "tdepth");
            return (Criteria) this;
        }

        public Criteria andJcIsNull() {
            addCriterion("Jc is null");
            return (Criteria) this;
        }

        public Criteria andJcIsNotNull() {
            addCriterion("Jc is not null");
            return (Criteria) this;
        }

        public Criteria andJcEqualTo(Double value) {
            addCriterion("Jc =", value, "jc");
            return (Criteria) this;
        }

        public Criteria andJcNotEqualTo(Double value) {
            addCriterion("Jc <>", value, "jc");
            return (Criteria) this;
        }

        public Criteria andJcGreaterThan(Double value) {
            addCriterion("Jc >", value, "jc");
            return (Criteria) this;
        }

        public Criteria andJcGreaterThanOrEqualTo(Double value) {
            addCriterion("Jc >=", value, "jc");
            return (Criteria) this;
        }

        public Criteria andJcLessThan(Double value) {
            addCriterion("Jc <", value, "jc");
            return (Criteria) this;
        }

        public Criteria andJcLessThanOrEqualTo(Double value) {
            addCriterion("Jc <=", value, "jc");
            return (Criteria) this;
        }

        public Criteria andJcIn(List<Double> values) {
            addCriterion("Jc in", values, "jc");
            return (Criteria) this;
        }

        public Criteria andJcNotIn(List<Double> values) {
            addCriterion("Jc not in", values, "jc");
            return (Criteria) this;
        }

        public Criteria andJcBetween(Double value1, Double value2) {
            addCriterion("Jc between", value1, value2, "jc");
            return (Criteria) this;
        }

        public Criteria andJcNotBetween(Double value1, Double value2) {
            addCriterion("Jc not between", value1, value2, "jc");
            return (Criteria) this;
        }

        public Criteria andGcjkIsNull() {
            addCriterion("Gcjk is null");
            return (Criteria) this;
        }

        public Criteria andGcjkIsNotNull() {
            addCriterion("Gcjk is not null");
            return (Criteria) this;
        }

        public Criteria andGcjkEqualTo(String value) {
            addCriterion("Gcjk =", value, "gcjk");
            return (Criteria) this;
        }

        public Criteria andGcjkNotEqualTo(String value) {
            addCriterion("Gcjk <>", value, "gcjk");
            return (Criteria) this;
        }

        public Criteria andGcjkGreaterThan(String value) {
            addCriterion("Gcjk >", value, "gcjk");
            return (Criteria) this;
        }

        public Criteria andGcjkGreaterThanOrEqualTo(String value) {
            addCriterion("Gcjk >=", value, "gcjk");
            return (Criteria) this;
        }

        public Criteria andGcjkLessThan(String value) {
            addCriterion("Gcjk <", value, "gcjk");
            return (Criteria) this;
        }

        public Criteria andGcjkLessThanOrEqualTo(String value) {
            addCriterion("Gcjk <=", value, "gcjk");
            return (Criteria) this;
        }

        public Criteria andGcjkLike(String value) {
            addCriterion("Gcjk like", value, "gcjk");
            return (Criteria) this;
        }

        public Criteria andGcjkNotLike(String value) {
            addCriterion("Gcjk not like", value, "gcjk");
            return (Criteria) this;
        }

        public Criteria andGcjkIn(List<String> values) {
            addCriterion("Gcjk in", values, "gcjk");
            return (Criteria) this;
        }

        public Criteria andGcjkNotIn(List<String> values) {
            addCriterion("Gcjk not in", values, "gcjk");
            return (Criteria) this;
        }

        public Criteria andGcjkBetween(String value1, String value2) {
            addCriterion("Gcjk between", value1, value2, "gcjk");
            return (Criteria) this;
        }

        public Criteria andGcjkNotBetween(String value1, String value2) {
            addCriterion("Gcjk not between", value1, value2, "gcjk");
            return (Criteria) this;
        }

        public Criteria andXybjhIsNull() {
            addCriterion("Xybjh is null");
            return (Criteria) this;
        }

        public Criteria andXybjhIsNotNull() {
            addCriterion("Xybjh is not null");
            return (Criteria) this;
        }

        public Criteria andXybjhEqualTo(String value) {
            addCriterion("Xybjh =", value, "xybjh");
            return (Criteria) this;
        }

        public Criteria andXybjhNotEqualTo(String value) {
            addCriterion("Xybjh <>", value, "xybjh");
            return (Criteria) this;
        }

        public Criteria andXybjhGreaterThan(String value) {
            addCriterion("Xybjh >", value, "xybjh");
            return (Criteria) this;
        }

        public Criteria andXybjhGreaterThanOrEqualTo(String value) {
            addCriterion("Xybjh >=", value, "xybjh");
            return (Criteria) this;
        }

        public Criteria andXybjhLessThan(String value) {
            addCriterion("Xybjh <", value, "xybjh");
            return (Criteria) this;
        }

        public Criteria andXybjhLessThanOrEqualTo(String value) {
            addCriterion("Xybjh <=", value, "xybjh");
            return (Criteria) this;
        }

        public Criteria andXybjhLike(String value) {
            addCriterion("Xybjh like", value, "xybjh");
            return (Criteria) this;
        }

        public Criteria andXybjhNotLike(String value) {
            addCriterion("Xybjh not like", value, "xybjh");
            return (Criteria) this;
        }

        public Criteria andXybjhIn(List<String> values) {
            addCriterion("Xybjh in", values, "xybjh");
            return (Criteria) this;
        }

        public Criteria andXybjhNotIn(List<String> values) {
            addCriterion("Xybjh not in", values, "xybjh");
            return (Criteria) this;
        }

        public Criteria andXybjhBetween(String value1, String value2) {
            addCriterion("Xybjh between", value1, value2, "xybjh");
            return (Criteria) this;
        }

        public Criteria andXybjhNotBetween(String value1, String value2) {
            addCriterion("Xybjh not between", value1, value2, "xybjh");
            return (Criteria) this;
        }

        public Criteria andHbrIsNull() {
            addCriterion("Hbr is null");
            return (Criteria) this;
        }

        public Criteria andHbrIsNotNull() {
            addCriterion("Hbr is not null");
            return (Criteria) this;
        }

        public Criteria andHbrEqualTo(String value) {
            addCriterion("Hbr =", value, "hbr");
            return (Criteria) this;
        }

        public Criteria andHbrNotEqualTo(String value) {
            addCriterion("Hbr <>", value, "hbr");
            return (Criteria) this;
        }

        public Criteria andHbrGreaterThan(String value) {
            addCriterion("Hbr >", value, "hbr");
            return (Criteria) this;
        }

        public Criteria andHbrGreaterThanOrEqualTo(String value) {
            addCriterion("Hbr >=", value, "hbr");
            return (Criteria) this;
        }

        public Criteria andHbrLessThan(String value) {
            addCriterion("Hbr <", value, "hbr");
            return (Criteria) this;
        }

        public Criteria andHbrLessThanOrEqualTo(String value) {
            addCriterion("Hbr <=", value, "hbr");
            return (Criteria) this;
        }

        public Criteria andHbrLike(String value) {
            addCriterion("Hbr like", value, "hbr");
            return (Criteria) this;
        }

        public Criteria andHbrNotLike(String value) {
            addCriterion("Hbr not like", value, "hbr");
            return (Criteria) this;
        }

        public Criteria andHbrIn(List<String> values) {
            addCriterion("Hbr in", values, "hbr");
            return (Criteria) this;
        }

        public Criteria andHbrNotIn(List<String> values) {
            addCriterion("Hbr not in", values, "hbr");
            return (Criteria) this;
        }

        public Criteria andHbrBetween(String value1, String value2) {
            addCriterion("Hbr between", value1, value2, "hbr");
            return (Criteria) this;
        }

        public Criteria andHbrNotBetween(String value1, String value2) {
            addCriterion("Hbr not between", value1, value2, "hbr");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("CreateTime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("CreateTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterion("CreateTime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterion("CreateTime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterion("CreateTime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CreateTime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterion("CreateTime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("CreateTime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("CreateTime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("CreateTime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("CreateTime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("CreateTime not between", value1, value2, "createtime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table well_xw_daily
     *
     * @mbggenerated do_not_delete_during_merge Tue Jun 26 17:52:59 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table well_xw_daily
     *
     * @mbggenerated Tue Jun 26 17:52:59 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}