package com.partymasses.modules.dao.mybatis.entity;

public class TestQuestionKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_question.QuestionId
     *
     * @mbggenerated Mon Apr 02 14:51:13 CST 2018
     */
    private Integer questionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_question.TestId
     *
     * @mbggenerated Mon Apr 02 14:51:13 CST 2018
     */
    private Integer testid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_question.QuestionId
     *
     * @return the value of test_question.QuestionId
     *
     * @mbggenerated Mon Apr 02 14:51:13 CST 2018
     */
    public Integer getQuestionid() {
        return questionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_question.QuestionId
     *
     * @param questionid the value for test_question.QuestionId
     *
     * @mbggenerated Mon Apr 02 14:51:13 CST 2018
     */
    public void setQuestionid(Integer questionid) {
        this.questionid = questionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_question.TestId
     *
     * @return the value of test_question.TestId
     *
     * @mbggenerated Mon Apr 02 14:51:13 CST 2018
     */
    public Integer getTestid() {
        return testid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_question.TestId
     *
     * @param testid the value for test_question.TestId
     *
     * @mbggenerated Mon Apr 02 14:51:13 CST 2018
     */
    public void setTestid(Integer testid) {
        this.testid = testid;
    }
}