package com.bswebsite.modules.dao.mybatis.entity;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.Id
     *
     * @mbggenerated Mon Apr 02 13:50:21 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.Name
     *
     * @mbggenerated Mon Apr 02 13:50:21 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.Mobile
     *
     * @mbggenerated Mon Apr 02 13:50:21 CST 2018
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.Password
     *
     * @mbggenerated Mon Apr 02 13:50:21 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.Sex
     *
     * @mbggenerated Mon Apr 02 13:50:21 CST 2018
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.Birthday
     *
     * @mbggenerated Mon Apr 02 13:50:21 CST 2018
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.IdNo
     *
     * @mbggenerated Mon Apr 02 13:50:21 CST 2018
     */
    private String idno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.CreateTime
     *
     * @mbggenerated Mon Apr 02 13:50:21 CST 2018
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.UpdateTime
     *
     * @mbggenerated Mon Apr 02 13:50:21 CST 2018
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.RoleType
     *
     * @mbggenerated Mon Apr 02 13:50:21 CST 2018
     */
    private String roletype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.Id
     *
     * @return the value of users.Id
     *
     * @mbggenerated Mon Apr 02 13:50:21 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.Id
     *
     * @param id the value for users.Id
     *
     * @mbggenerated Mon Apr 02 13:50:21 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.Name
     *
     * @return the value of users.Name
     *
     * @mbggenerated Mon Apr 02 13:50:21 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.Name
     *
     * @param name the value for users.Name
     *
     * @mbggenerated Mon Apr 02 13:50:21 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.Mobile
     *
     * @return the value of users.Mobile
     *
     * @mbggenerated Mon Apr 02 13:50:21 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.Mobile
     *
     * @param mobile the value for users.Mobile
     *
     * @mbggenerated Mon Apr 02 13:50:21 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.Password
     *
     * @return the value of users.Password
     *
     * @mbggenerated Mon Apr 02 13:50:21 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.Password
     *
     * @param password the value for users.Password
     *
     * @mbggenerated Mon Apr 02 13:50:21 CST 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.Sex
     *
     * @return the value of users.Sex
     *
     * @mbggenerated Mon Apr 02 13:50:21 CST 2018
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.Sex
     *
     * @param sex the value for users.Sex
     *
     * @mbggenerated Mon Apr 02 13:50:21 CST 2018
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.Birthday
     *
     * @return the value of users.Birthday
     *
     * @mbggenerated Mon Apr 02 13:50:21 CST 2018
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.Birthday
     *
     * @param birthday the value for users.Birthday
     *
     * @mbggenerated Mon Apr 02 13:50:21 CST 2018
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.IdNo
     *
     * @return the value of users.IdNo
     *
     * @mbggenerated Mon Apr 02 13:50:21 CST 2018
     */
    public String getIdno() {
        return idno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.IdNo
     *
     * @param idno the value for users.IdNo
     *
     * @mbggenerated Mon Apr 02 13:50:21 CST 2018
     */
    public void setIdno(String idno) {
        this.idno = idno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.CreateTime
     *
     * @return the value of users.CreateTime
     *
     * @mbggenerated Mon Apr 02 13:50:21 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.CreateTime
     *
     * @param createtime the value for users.CreateTime
     *
     * @mbggenerated Mon Apr 02 13:50:21 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.UpdateTime
     *
     * @return the value of users.UpdateTime
     *
     * @mbggenerated Mon Apr 02 13:50:21 CST 2018
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.UpdateTime
     *
     * @param updatetime the value for users.UpdateTime
     *
     * @mbggenerated Mon Apr 02 13:50:21 CST 2018
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.RoleType
     *
     * @return the value of users.RoleType
     *
     * @mbggenerated Mon Apr 02 13:50:21 CST 2018
     */
    public String getRoletype() {
        return roletype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.RoleType
     *
     * @param roletype the value for users.RoleType
     *
     * @mbggenerated Mon Apr 02 13:50:21 CST 2018
     */
    public void setRoletype(String roletype) {
        this.roletype = roletype;
    }
}