package com.partymasses.modules.dao.mybatis.mapper;

import com.partymasses.modules.dao.dto.AtvDto;
import com.partymasses.modules.dao.mybatis.entity.ActivityUnits;
import com.partymasses.modules.dao.mybatis.entity.ActivityUnitsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ActivityUnitsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_units
     *
     * @mbggenerated Tue Mar 27 09:01:40 CST 2018
     */
    int countByExample(ActivityUnitsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_units
     *
     * @mbggenerated Tue Mar 27 09:01:40 CST 2018
     */
    int deleteByExample(ActivityUnitsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_units
     *
     * @mbggenerated Tue Mar 27 09:01:40 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_units
     *
     * @mbggenerated Tue Mar 27 09:01:40 CST 2018
     */
    int insert(ActivityUnits record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_units
     *
     * @mbggenerated Tue Mar 27 09:01:40 CST 2018
     */
    int insertSelective(ActivityUnits record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_units
     *
     * @mbggenerated Tue Mar 27 09:01:40 CST 2018
     */
    List<ActivityUnits> selectByExample(ActivityUnitsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_units
     *
     * @mbggenerated Tue Mar 27 09:01:40 CST 2018
     */
    ActivityUnits selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_units
     *
     * @mbggenerated Tue Mar 27 09:01:40 CST 2018
     */
    int updateByExampleSelective(@Param("record") ActivityUnits record, @Param("example") ActivityUnitsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_units
     *
     * @mbggenerated Tue Mar 27 09:01:40 CST 2018
     */
    int updateByExample(@Param("record") ActivityUnits record, @Param("example") ActivityUnitsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_units
     *
     * @mbggenerated Tue Mar 27 09:01:40 CST 2018
     */
    int updateByPrimaryKeySelective(ActivityUnits record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_units
     *
     * @mbggenerated Tue Mar 27 09:01:40 CST 2018
     */
    int updateByPrimaryKey(ActivityUnits record);
    /**
     * 判断单位是否已经分配
     *
     * @mbggenerated Tue Mar 27 09:01:40 CST 2018
     */
    List<ActivityUnits> selectIsExist(AtvDto atvdto);
    
    /**
     * 分配单位
     *
     * @mbggenerated Tue Mar 27 09:01:40 CST 2018
     */
    int distributeActivity(AtvDto atvdto);
}