package com.partymasses.modules.dao.mybatis.mapper;

import com.partymasses.modules.dao.mybatis.entity.ActivityUsers;
import com.partymasses.modules.dao.mybatis.entity.ActivityUsersExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ActivityUsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_users
     *
     * @mbggenerated Tue Mar 27 09:01:40 CST 2018
     */
    int countByExample(ActivityUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_users
     *
     * @mbggenerated Tue Mar 27 09:01:40 CST 2018
     */
    int deleteByExample(ActivityUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_users
     *
     * @mbggenerated Tue Mar 27 09:01:40 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_users
     *
     * @mbggenerated Tue Mar 27 09:01:40 CST 2018
     */
    int insert(ActivityUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_users
     *
     * @mbggenerated Tue Mar 27 09:01:40 CST 2018
     */
    int insertSelective(ActivityUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_users
     *
     * @mbggenerated Tue Mar 27 09:01:40 CST 2018
     */
    List<ActivityUsers> selectByExample(ActivityUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_users
     *
     * @mbggenerated Tue Mar 27 09:01:40 CST 2018
     */
    ActivityUsers selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_users
     *
     * @mbggenerated Tue Mar 27 09:01:40 CST 2018
     */
    int updateByExampleSelective(@Param("record") ActivityUsers record, @Param("example") ActivityUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_users
     *
     * @mbggenerated Tue Mar 27 09:01:40 CST 2018
     */
    int updateByExample(@Param("record") ActivityUsers record, @Param("example") ActivityUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_users
     *
     * @mbggenerated Tue Mar 27 09:01:40 CST 2018
     */
    int updateByPrimaryKeySelective(ActivityUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_users
     *
     * @mbggenerated Tue Mar 27 09:01:40 CST 2018
     */
    int updateByPrimaryKey(ActivityUsers record);
}