package com.partymasses.modules.dao.mybatis.mapper;

import com.partymasses.modules.dao.mybatis.entity.PartyFamily;
import com.partymasses.modules.dao.mybatis.entity.PartyFamilyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PartyFamilyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table party_family
     *
     * @mbggenerated Thu Mar 22 13:51:41 CST 2018
     */
    int countByExample(PartyFamilyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table party_family
     *
     * @mbggenerated Thu Mar 22 13:51:41 CST 2018
     */
    int deleteByExample(PartyFamilyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table party_family
     *
     * @mbggenerated Thu Mar 22 13:51:41 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table party_family
     *
     * @mbggenerated Thu Mar 22 13:51:41 CST 2018
     */
    int insert(PartyFamily record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table party_family
     *
     * @mbggenerated Thu Mar 22 13:51:41 CST 2018
     */
    int insertSelective(PartyFamily record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table party_family
     *
     * @mbggenerated Thu Mar 22 13:51:41 CST 2018
     */
    List<PartyFamily> selectByExample(PartyFamilyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table party_family
     *
     * @mbggenerated Thu Mar 22 13:51:41 CST 2018
     */
    PartyFamily selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table party_family
     *
     * @mbggenerated Thu Mar 22 13:51:41 CST 2018
     */
    int updateByExampleSelective(@Param("record") PartyFamily record, @Param("example") PartyFamilyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table party_family
     *
     * @mbggenerated Thu Mar 22 13:51:41 CST 2018
     */
    int updateByExample(@Param("record") PartyFamily record, @Param("example") PartyFamilyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table party_family
     *
     * @mbggenerated Thu Mar 22 13:51:41 CST 2018
     */
    int updateByPrimaryKeySelective(PartyFamily record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table party_family
     *
     * @mbggenerated Thu Mar 22 13:51:41 CST 2018
     */
    int updateByPrimaryKey(PartyFamily record);
}