package com.partymasses.modules.dao.mybatis.mapper;

import com.partymasses.modules.dao.mybatis.entity.TestQuestion;
import com.partymasses.modules.dao.mybatis.entity.TestQuestionExample;
import com.partymasses.modules.dao.mybatis.entity.TestQuestionKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TestQuestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_question
     *
     * @mbggenerated Mon Apr 02 14:51:13 CST 2018
     */
    int countByExample(TestQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_question
     *
     * @mbggenerated Mon Apr 02 14:51:13 CST 2018
     */
    int deleteByExample(TestQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_question
     *
     * @mbggenerated Mon Apr 02 14:51:13 CST 2018
     */
    int deleteByPrimaryKey(TestQuestionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_question
     *
     * @mbggenerated Mon Apr 02 14:51:13 CST 2018
     */
    int insert(TestQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_question
     *
     * @mbggenerated Mon Apr 02 14:51:13 CST 2018
     */
    int insertSelective(TestQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_question
     *
     * @mbggenerated Mon Apr 02 14:51:13 CST 2018
     */
    List<TestQuestion> selectByExample(TestQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_question
     *
     * @mbggenerated Mon Apr 02 14:51:13 CST 2018
     */
    TestQuestion selectByPrimaryKey(TestQuestionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_question
     *
     * @mbggenerated Mon Apr 02 14:51:13 CST 2018
     */
    int updateByExampleSelective(@Param("record") TestQuestion record, @Param("example") TestQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_question
     *
     * @mbggenerated Mon Apr 02 14:51:13 CST 2018
     */
    int updateByExample(@Param("record") TestQuestion record, @Param("example") TestQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_question
     *
     * @mbggenerated Mon Apr 02 14:51:13 CST 2018
     */
    int updateByPrimaryKeySelective(TestQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_question
     *
     * @mbggenerated Mon Apr 02 14:51:13 CST 2018
     */
    int updateByPrimaryKey(TestQuestion record);
}