package cn.caecc.erp.modules.dao.mybatis.mapper;

import cn.caecc.erp.modules.dao.mybatis.entity.ContractGoodsRelationship;
import cn.caecc.erp.modules.dao.mybatis.entity.ContractGoodsRelationshipExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ContractGoodsRelationshipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_goods_relationship
     *
     * @mbggenerated Tue Jul 03 09:09:00 CST 2018
     */
    int countByExample(ContractGoodsRelationshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_goods_relationship
     *
     * @mbggenerated Tue Jul 03 09:09:00 CST 2018
     */
    int deleteByExample(ContractGoodsRelationshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_goods_relationship
     *
     * @mbggenerated Tue Jul 03 09:09:00 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_goods_relationship
     *
     * @mbggenerated Tue Jul 03 09:09:00 CST 2018
     */
    int insert(ContractGoodsRelationship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_goods_relationship
     *
     * @mbggenerated Tue Jul 03 09:09:00 CST 2018
     */
    int insertSelective(ContractGoodsRelationship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_goods_relationship
     *
     * @mbggenerated Tue Jul 03 09:09:00 CST 2018
     */
    List<ContractGoodsRelationship> selectByExample(ContractGoodsRelationshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_goods_relationship
     *
     * @mbggenerated Tue Jul 03 09:09:00 CST 2018
     */
    ContractGoodsRelationship selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_goods_relationship
     *
     * @mbggenerated Tue Jul 03 09:09:00 CST 2018
     */
    int updateByExampleSelective(@Param("record") ContractGoodsRelationship record, @Param("example") ContractGoodsRelationshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_goods_relationship
     *
     * @mbggenerated Tue Jul 03 09:09:00 CST 2018
     */
    int updateByExample(@Param("record") ContractGoodsRelationship record, @Param("example") ContractGoodsRelationshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_goods_relationship
     *
     * @mbggenerated Tue Jul 03 09:09:00 CST 2018
     */
    int updateByPrimaryKeySelective(ContractGoodsRelationship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_goods_relationship
     *
     * @mbggenerated Tue Jul 03 09:09:00 CST 2018
     */
    int updateByPrimaryKey(ContractGoodsRelationship record);
}