package cn.caecc.erp.modules.dao.mybatis.entity;

import java.io.Serializable;
import java.util.Date;

public class Message implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.MessageId
     *
     * @mbggenerated Tue Jul 10 15:04:57 CST 2018
     */
    private Integer messageid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.MessageTypeId
     *
     * @mbggenerated Tue Jul 10 15:04:57 CST 2018
     */
    private Integer messagetypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.UId
     *
     * @mbggenerated Tue Jul 10 15:04:57 CST 2018
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.Title
     *
     * @mbggenerated Tue Jul 10 15:04:57 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.Content
     *
     * @mbggenerated Tue Jul 10 15:04:57 CST 2018
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.Status
     *
     * @mbggenerated Tue Jul 10 15:04:57 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.CreateTime
     *
     * @mbggenerated Tue Jul 10 15:04:57 CST 2018
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table message
     *
     * @mbggenerated Tue Jul 10 15:04:57 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.MessageId
     *
     * @return the value of message.MessageId
     *
     * @mbggenerated Tue Jul 10 15:04:57 CST 2018
     */
    public Integer getMessageid() {
        return messageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.MessageId
     *
     * @param messageid the value for message.MessageId
     *
     * @mbggenerated Tue Jul 10 15:04:57 CST 2018
     */
    public void setMessageid(Integer messageid) {
        this.messageid = messageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.MessageTypeId
     *
     * @return the value of message.MessageTypeId
     *
     * @mbggenerated Tue Jul 10 15:04:57 CST 2018
     */
    public Integer getMessagetypeid() {
        return messagetypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.MessageTypeId
     *
     * @param messagetypeid the value for message.MessageTypeId
     *
     * @mbggenerated Tue Jul 10 15:04:57 CST 2018
     */
    public void setMessagetypeid(Integer messagetypeid) {
        this.messagetypeid = messagetypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.UId
     *
     * @return the value of message.UId
     *
     * @mbggenerated Tue Jul 10 15:04:57 CST 2018
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.UId
     *
     * @param uid the value for message.UId
     *
     * @mbggenerated Tue Jul 10 15:04:57 CST 2018
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.Title
     *
     * @return the value of message.Title
     *
     * @mbggenerated Tue Jul 10 15:04:57 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.Title
     *
     * @param title the value for message.Title
     *
     * @mbggenerated Tue Jul 10 15:04:57 CST 2018
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.Content
     *
     * @return the value of message.Content
     *
     * @mbggenerated Tue Jul 10 15:04:57 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.Content
     *
     * @param content the value for message.Content
     *
     * @mbggenerated Tue Jul 10 15:04:57 CST 2018
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.Status
     *
     * @return the value of message.Status
     *
     * @mbggenerated Tue Jul 10 15:04:57 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.Status
     *
     * @param status the value for message.Status
     *
     * @mbggenerated Tue Jul 10 15:04:57 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.CreateTime
     *
     * @return the value of message.CreateTime
     *
     * @mbggenerated Tue Jul 10 15:04:57 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.CreateTime
     *
     * @param createtime the value for message.CreateTime
     *
     * @mbggenerated Tue Jul 10 15:04:57 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}