package cn.caecc.erp.modules.dao.mybatis.entity;

import java.io.Serializable;

public class MessageType implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_type.MessageTypeId
     *
     * @mbggenerated Sat Aug 04 17:33:02 CST 2018
     */
    private Integer messagetypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_type.Name
     *
     * @mbggenerated Sat Aug 04 17:33:02 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_type.Description
     *
     * @mbggenerated Sat Aug 04 17:33:02 CST 2018
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table message_type
     *
     * @mbggenerated Sat Aug 04 17:33:02 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_type.MessageTypeId
     *
     * @return the value of message_type.MessageTypeId
     *
     * @mbggenerated Sat Aug 04 17:33:02 CST 2018
     */
    public Integer getMessagetypeid() {
        return messagetypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_type.MessageTypeId
     *
     * @param messagetypeid the value for message_type.MessageTypeId
     *
     * @mbggenerated Sat Aug 04 17:33:02 CST 2018
     */
    public void setMessagetypeid(Integer messagetypeid) {
        this.messagetypeid = messagetypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_type.Name
     *
     * @return the value of message_type.Name
     *
     * @mbggenerated Sat Aug 04 17:33:02 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_type.Name
     *
     * @param name the value for message_type.Name
     *
     * @mbggenerated Sat Aug 04 17:33:02 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_type.Description
     *
     * @return the value of message_type.Description
     *
     * @mbggenerated Sat Aug 04 17:33:02 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_type.Description
     *
     * @param description the value for message_type.Description
     *
     * @mbggenerated Sat Aug 04 17:33:02 CST 2018
     */
    public void setDescription(String description) {
        this.description = description;
    }
}