package cn.caecc.erp.modules.dao.mybatis.mapper;

import cn.caecc.erp.modules.dao.mybatis.entity.WorkingPlan;
import cn.caecc.erp.modules.dao.mybatis.entity.WorkingPlanExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WorkingPlanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table working_plan
     *
     * @mbggenerated Mon Jul 30 16:24:37 CST 2018
     */
    int countByExample(WorkingPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table working_plan
     *
     * @mbggenerated Mon Jul 30 16:24:37 CST 2018
     */
    int deleteByExample(WorkingPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table working_plan
     *
     * @mbggenerated Mon Jul 30 16:24:37 CST 2018
     */
    int deleteByPrimaryKey(Integer workingplanid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table working_plan
     *
     * @mbggenerated Mon Jul 30 16:24:37 CST 2018
     */
    int insert(WorkingPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table working_plan
     *
     * @mbggenerated Mon Jul 30 16:24:37 CST 2018
     */
    int insertSelective(WorkingPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table working_plan
     *
     * @mbggenerated Mon Jul 30 16:24:37 CST 2018
     */
    List<WorkingPlan> selectByExample(WorkingPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table working_plan
     *
     * @mbggenerated Mon Jul 30 16:24:37 CST 2018
     */
    WorkingPlan selectByPrimaryKey(Integer workingplanid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table working_plan
     *
     * @mbggenerated Mon Jul 30 16:24:37 CST 2018
     */
    int updateByExampleSelective(@Param("record") WorkingPlan record, @Param("example") WorkingPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table working_plan
     *
     * @mbggenerated Mon Jul 30 16:24:37 CST 2018
     */
    int updateByExample(@Param("record") WorkingPlan record, @Param("example") WorkingPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table working_plan
     *
     * @mbggenerated Mon Jul 30 16:24:37 CST 2018
     */
    int updateByPrimaryKeySelective(WorkingPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table working_plan
     *
     * @mbggenerated Mon Jul 30 16:24:37 CST 2018
     */
    int updateByPrimaryKey(WorkingPlan record);
}