package cn.caecc.erp.modules.dao.mybatis.entity;

import java.io.Serializable;

public class Goods implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.Code
     *
     * @mbggenerated Thu May 24 14:05:44 CST 2018
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.PCode
     *
     * @mbggenerated Thu May 24 14:05:44 CST 2018
     */
    private String pcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.Id
     *
     * @mbggenerated Thu May 24 14:05:44 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.Grade
     *
     * @mbggenerated Thu May 24 14:05:44 CST 2018
     */
    private Integer grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.Name
     *
     * @mbggenerated Thu May 24 14:05:44 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.Model
     *
     * @mbggenerated Thu May 24 14:05:44 CST 2018
     */
    private String model;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.Unit
     *
     * @mbggenerated Thu May 24 14:05:44 CST 2018
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.Remarks
     *
     * @mbggenerated Thu May 24 14:05:44 CST 2018
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table goods
     *
     * @mbggenerated Thu May 24 14:05:44 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.Code
     *
     * @return the value of goods.Code
     *
     * @mbggenerated Thu May 24 14:05:44 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.Code
     *
     * @param code the value for goods.Code
     *
     * @mbggenerated Thu May 24 14:05:44 CST 2018
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.PCode
     *
     * @return the value of goods.PCode
     *
     * @mbggenerated Thu May 24 14:05:44 CST 2018
     */
    public String getPcode() {
        return pcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.PCode
     *
     * @param pcode the value for goods.PCode
     *
     * @mbggenerated Thu May 24 14:05:44 CST 2018
     */
    public void setPcode(String pcode) {
        this.pcode = pcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.Id
     *
     * @return the value of goods.Id
     *
     * @mbggenerated Thu May 24 14:05:44 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.Id
     *
     * @param id the value for goods.Id
     *
     * @mbggenerated Thu May 24 14:05:44 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.Grade
     *
     * @return the value of goods.Grade
     *
     * @mbggenerated Thu May 24 14:05:44 CST 2018
     */
    public Integer getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.Grade
     *
     * @param grade the value for goods.Grade
     *
     * @mbggenerated Thu May 24 14:05:44 CST 2018
     */
    public void setGrade(Integer grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.Name
     *
     * @return the value of goods.Name
     *
     * @mbggenerated Thu May 24 14:05:44 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.Name
     *
     * @param name the value for goods.Name
     *
     * @mbggenerated Thu May 24 14:05:44 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.Model
     *
     * @return the value of goods.Model
     *
     * @mbggenerated Thu May 24 14:05:44 CST 2018
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.Model
     *
     * @param model the value for goods.Model
     *
     * @mbggenerated Thu May 24 14:05:44 CST 2018
     */
    public void setModel(String model) {
        this.model = model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.Unit
     *
     * @return the value of goods.Unit
     *
     * @mbggenerated Thu May 24 14:05:44 CST 2018
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.Unit
     *
     * @param unit the value for goods.Unit
     *
     * @mbggenerated Thu May 24 14:05:44 CST 2018
     */
    public void setUnit(String unit) {
        this.unit = unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.Remarks
     *
     * @return the value of goods.Remarks
     *
     * @mbggenerated Thu May 24 14:05:44 CST 2018
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.Remarks
     *
     * @param remarks the value for goods.Remarks
     *
     * @mbggenerated Thu May 24 14:05:44 CST 2018
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
}