package cn.caecc.erp.modules.dao.mybatis.mapper;

import cn.caecc.erp.modules.dao.mybatis.entity.MaterialActivitiApply;
import cn.caecc.erp.modules.dao.mybatis.entity.MaterialActivitiApplyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MaterialActivitiApplyMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table material_activiti_apply
	 * @mbggenerated  Thu Jul 12 18:17:50 CST 2018
	 */
	int countByExample(MaterialActivitiApplyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table material_activiti_apply
	 * @mbggenerated  Thu Jul 12 18:17:50 CST 2018
	 */
	int deleteByExample(MaterialActivitiApplyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table material_activiti_apply
	 * @mbggenerated  Thu Jul 12 18:17:50 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table material_activiti_apply
	 * @mbggenerated  Thu Jul 12 18:17:50 CST 2018
	 */
	int insert(MaterialActivitiApply record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table material_activiti_apply
	 * @mbggenerated  Thu Jul 12 18:17:50 CST 2018
	 */
	int insertSelective(MaterialActivitiApply record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table material_activiti_apply
	 * @mbggenerated  Thu Jul 12 18:17:50 CST 2018
	 */
	List<MaterialActivitiApply> selectByExample(MaterialActivitiApplyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table material_activiti_apply
	 * @mbggenerated  Thu Jul 12 18:17:50 CST 2018
	 */
	MaterialActivitiApply selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table material_activiti_apply
	 * @mbggenerated  Thu Jul 12 18:17:50 CST 2018
	 */
	int updateByExampleSelective(@Param("record") MaterialActivitiApply record,
			@Param("example") MaterialActivitiApplyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table material_activiti_apply
	 * @mbggenerated  Thu Jul 12 18:17:50 CST 2018
	 */
	int updateByExample(@Param("record") MaterialActivitiApply record,
			@Param("example") MaterialActivitiApplyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table material_activiti_apply
	 * @mbggenerated  Thu Jul 12 18:17:50 CST 2018
	 */
	int updateByPrimaryKeySelective(MaterialActivitiApply record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table material_activiti_apply
	 * @mbggenerated  Thu Jul 12 18:17:50 CST 2018
	 */
	int updateByPrimaryKey(MaterialActivitiApply record);
}