package cn.caecc.erp.modules.dao.mybatis.mapper;

import cn.caecc.erp.modules.dao.mybatis.entity.CardActivitiApply;
import cn.caecc.erp.modules.dao.mybatis.entity.CardActivitiApplyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CardActivitiApplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_activiti_apply
     *
     * @mbggenerated Tue Jun 26 14:25:02 CST 2018
     */
    int countByExample(CardActivitiApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_activiti_apply
     *
     * @mbggenerated Tue Jun 26 14:25:02 CST 2018
     */
    int deleteByExample(CardActivitiApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_activiti_apply
     *
     * @mbggenerated Tue Jun 26 14:25:02 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_activiti_apply
     *
     * @mbggenerated Tue Jun 26 14:25:02 CST 2018
     */
    int insert(CardActivitiApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_activiti_apply
     *
     * @mbggenerated Tue Jun 26 14:25:02 CST 2018
     */
    int insertSelective(CardActivitiApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_activiti_apply
     *
     * @mbggenerated Tue Jun 26 14:25:02 CST 2018
     */
    List<CardActivitiApply> selectByExample(CardActivitiApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_activiti_apply
     *
     * @mbggenerated Tue Jun 26 14:25:02 CST 2018
     */
    CardActivitiApply selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_activiti_apply
     *
     * @mbggenerated Tue Jun 26 14:25:02 CST 2018
     */
    int updateByExampleSelective(@Param("record") CardActivitiApply record, @Param("example") CardActivitiApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_activiti_apply
     *
     * @mbggenerated Tue Jun 26 14:25:02 CST 2018
     */
    int updateByExample(@Param("record") CardActivitiApply record, @Param("example") CardActivitiApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_activiti_apply
     *
     * @mbggenerated Tue Jun 26 14:25:02 CST 2018
     */
    int updateByPrimaryKeySelective(CardActivitiApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_activiti_apply
     *
     * @mbggenerated Tue Jun 26 14:25:02 CST 2018
     */
    int updateByPrimaryKey(CardActivitiApply record);
}