package cn.caecc.erp.modules.dao.mybatis.entity;

import java.io.Serializable;
import java.util.Date;

public class WellDaily implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column well_daily_sum.Id
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column well_daily_sum.WellId
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    private Integer wellid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column well_daily_sum.Did
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    private Integer did;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column well_daily_sum.Jb
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    private String jb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column well_daily_sum.Kzrq
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    private Date kzrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column well_daily_sum.Zbt
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    private Integer zbt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column well_daily_sum.Sjt
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    private Integer sjt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column well_daily_sum.Syt
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    private Integer syt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column well_daily_sum.Sjjs
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    private Double sjjs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column well_daily_sum.TDepth
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    private Double tdepth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column well_daily_sum.Jdcw
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    private String jdcw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column well_daily_sum.Ztcc
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    private String ztcc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column well_daily_sum.Rjc
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    private Double rjc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column well_daily_sum.Yjc
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    private Double yjc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column well_daily_sum.Nljjc
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    private Double nljjc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column well_daily_sum.Zy
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    private String zy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column well_daily_sum.Zs
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    private String zs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column well_daily_sum.Pl
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    private String pl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column well_daily_sum.Py
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    private String py;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column well_daily_sum.Njmd
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    private String njmd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column well_daily_sum.Ldnd
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    private String ldnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column well_daily_sum.Ss
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    private String ss;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column well_daily_sum.Ztcx
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    private String ztcx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column well_daily_sum.Gk
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    private String gk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column well_daily_sum.Zjzh
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    private String zjzh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column well_daily_sum.LogDate
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    private Date logdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column well_daily_sum.SumRjc
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    private Double sumrjc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column well_daily_sum.SumYlj
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    private Double sumylj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column well_daily_sum.SumNlj
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    private Double sumnlj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column well_daily_sum.Kzjsl
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    private Integer kzjsl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column well_daily_sum.Kzjjh
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    private String kzjjh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column well_daily_sum.Wzjsl
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    private Integer wzjsl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column well_daily_sum.Wzjjh
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    private String wzjjh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column well_daily_sum.Jjsl
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    private Integer jjsl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column well_daily_sum.Jjjh
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    private String jjjh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column well_daily_sum.CreateTime
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column well_daily_sum.Zjdt
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    private Integer zjdt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table well_daily_sum
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column well_daily_sum.Id
     *
     * @return the value of well_daily_sum.Id
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column well_daily_sum.Id
     *
     * @param id the value for well_daily_sum.Id
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column well_daily_sum.WellId
     *
     * @return the value of well_daily_sum.WellId
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    public Integer getWellid() {
        return wellid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column well_daily_sum.WellId
     *
     * @param wellid the value for well_daily_sum.WellId
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    public void setWellid(Integer wellid) {
        this.wellid = wellid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column well_daily_sum.Did
     *
     * @return the value of well_daily_sum.Did
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    public Integer getDid() {
        return did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column well_daily_sum.Did
     *
     * @param did the value for well_daily_sum.Did
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    public void setDid(Integer did) {
        this.did = did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column well_daily_sum.Jb
     *
     * @return the value of well_daily_sum.Jb
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    public String getJb() {
        return jb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column well_daily_sum.Jb
     *
     * @param jb the value for well_daily_sum.Jb
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    public void setJb(String jb) {
        this.jb = jb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column well_daily_sum.Kzrq
     *
     * @return the value of well_daily_sum.Kzrq
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    public Date getKzrq() {
        return kzrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column well_daily_sum.Kzrq
     *
     * @param kzrq the value for well_daily_sum.Kzrq
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    public void setKzrq(Date kzrq) {
        this.kzrq = kzrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column well_daily_sum.Zbt
     *
     * @return the value of well_daily_sum.Zbt
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    public Integer getZbt() {
        return zbt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column well_daily_sum.Zbt
     *
     * @param zbt the value for well_daily_sum.Zbt
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    public void setZbt(Integer zbt) {
        this.zbt = zbt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column well_daily_sum.Sjt
     *
     * @return the value of well_daily_sum.Sjt
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    public Integer getSjt() {
        return sjt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column well_daily_sum.Sjt
     *
     * @param sjt the value for well_daily_sum.Sjt
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    public void setSjt(Integer sjt) {
        this.sjt = sjt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column well_daily_sum.Syt
     *
     * @return the value of well_daily_sum.Syt
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    public Integer getSyt() {
        return syt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column well_daily_sum.Syt
     *
     * @param syt the value for well_daily_sum.Syt
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    public void setSyt(Integer syt) {
        this.syt = syt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column well_daily_sum.Sjjs
     *
     * @return the value of well_daily_sum.Sjjs
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    public Double getSjjs() {
        return sjjs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column well_daily_sum.Sjjs
     *
     * @param sjjs the value for well_daily_sum.Sjjs
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    public void setSjjs(Double sjjs) {
        this.sjjs = sjjs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column well_daily_sum.TDepth
     *
     * @return the value of well_daily_sum.TDepth
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    public Double getTdepth() {
        return tdepth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column well_daily_sum.TDepth
     *
     * @param tdepth the value for well_daily_sum.TDepth
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    public void setTdepth(Double tdepth) {
        this.tdepth = tdepth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column well_daily_sum.Jdcw
     *
     * @return the value of well_daily_sum.Jdcw
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    public String getJdcw() {
        return jdcw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column well_daily_sum.Jdcw
     *
     * @param jdcw the value for well_daily_sum.Jdcw
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    public void setJdcw(String jdcw) {
        this.jdcw = jdcw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column well_daily_sum.Ztcc
     *
     * @return the value of well_daily_sum.Ztcc
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    public String getZtcc() {
        return ztcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column well_daily_sum.Ztcc
     *
     * @param ztcc the value for well_daily_sum.Ztcc
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    public void setZtcc(String ztcc) {
        this.ztcc = ztcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column well_daily_sum.Rjc
     *
     * @return the value of well_daily_sum.Rjc
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    public Double getRjc() {
        return rjc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column well_daily_sum.Rjc
     *
     * @param rjc the value for well_daily_sum.Rjc
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    public void setRjc(Double rjc) {
        this.rjc = rjc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column well_daily_sum.Yjc
     *
     * @return the value of well_daily_sum.Yjc
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    public Double getYjc() {
        return yjc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column well_daily_sum.Yjc
     *
     * @param yjc the value for well_daily_sum.Yjc
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    public void setYjc(Double yjc) {
        this.yjc = yjc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column well_daily_sum.Nljjc
     *
     * @return the value of well_daily_sum.Nljjc
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    public Double getNljjc() {
        return nljjc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column well_daily_sum.Nljjc
     *
     * @param nljjc the value for well_daily_sum.Nljjc
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    public void setNljjc(Double nljjc) {
        this.nljjc = nljjc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column well_daily_sum.Zy
     *
     * @return the value of well_daily_sum.Zy
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    public String getZy() {
        return zy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column well_daily_sum.Zy
     *
     * @param zy the value for well_daily_sum.Zy
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    public void setZy(String zy) {
        this.zy = zy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column well_daily_sum.Zs
     *
     * @return the value of well_daily_sum.Zs
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    public String getZs() {
        return zs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column well_daily_sum.Zs
     *
     * @param zs the value for well_daily_sum.Zs
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    public void setZs(String zs) {
        this.zs = zs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column well_daily_sum.Pl
     *
     * @return the value of well_daily_sum.Pl
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    public String getPl() {
        return pl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column well_daily_sum.Pl
     *
     * @param pl the value for well_daily_sum.Pl
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    public void setPl(String pl) {
        this.pl = pl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column well_daily_sum.Py
     *
     * @return the value of well_daily_sum.Py
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    public String getPy() {
        return py;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column well_daily_sum.Py
     *
     * @param py the value for well_daily_sum.Py
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    public void setPy(String py) {
        this.py = py;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column well_daily_sum.Njmd
     *
     * @return the value of well_daily_sum.Njmd
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    public String getNjmd() {
        return njmd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column well_daily_sum.Njmd
     *
     * @param njmd the value for well_daily_sum.Njmd
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    public void setNjmd(String njmd) {
        this.njmd = njmd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column well_daily_sum.Ldnd
     *
     * @return the value of well_daily_sum.Ldnd
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    public String getLdnd() {
        return ldnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column well_daily_sum.Ldnd
     *
     * @param ldnd the value for well_daily_sum.Ldnd
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    public void setLdnd(String ldnd) {
        this.ldnd = ldnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column well_daily_sum.Ss
     *
     * @return the value of well_daily_sum.Ss
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    public String getSs() {
        return ss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column well_daily_sum.Ss
     *
     * @param ss the value for well_daily_sum.Ss
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    public void setSs(String ss) {
        this.ss = ss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column well_daily_sum.Ztcx
     *
     * @return the value of well_daily_sum.Ztcx
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    public String getZtcx() {
        return ztcx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column well_daily_sum.Ztcx
     *
     * @param ztcx the value for well_daily_sum.Ztcx
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    public void setZtcx(String ztcx) {
        this.ztcx = ztcx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column well_daily_sum.Gk
     *
     * @return the value of well_daily_sum.Gk
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    public String getGk() {
        return gk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column well_daily_sum.Gk
     *
     * @param gk the value for well_daily_sum.Gk
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    public void setGk(String gk) {
        this.gk = gk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column well_daily_sum.Zjzh
     *
     * @return the value of well_daily_sum.Zjzh
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    public String getZjzh() {
        return zjzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column well_daily_sum.Zjzh
     *
     * @param zjzh the value for well_daily_sum.Zjzh
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    public void setZjzh(String zjzh) {
        this.zjzh = zjzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column well_daily_sum.LogDate
     *
     * @return the value of well_daily_sum.LogDate
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    public Date getLogdate() {
        return logdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column well_daily_sum.LogDate
     *
     * @param logdate the value for well_daily_sum.LogDate
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    public void setLogdate(Date logdate) {
        this.logdate = logdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column well_daily_sum.SumRjc
     *
     * @return the value of well_daily_sum.SumRjc
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    public Double getSumrjc() {
        return sumrjc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column well_daily_sum.SumRjc
     *
     * @param sumrjc the value for well_daily_sum.SumRjc
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    public void setSumrjc(Double sumrjc) {
        this.sumrjc = sumrjc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column well_daily_sum.SumYlj
     *
     * @return the value of well_daily_sum.SumYlj
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    public Double getSumylj() {
        return sumylj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column well_daily_sum.SumYlj
     *
     * @param sumylj the value for well_daily_sum.SumYlj
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    public void setSumylj(Double sumylj) {
        this.sumylj = sumylj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column well_daily_sum.SumNlj
     *
     * @return the value of well_daily_sum.SumNlj
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    public Double getSumnlj() {
        return sumnlj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column well_daily_sum.SumNlj
     *
     * @param sumnlj the value for well_daily_sum.SumNlj
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    public void setSumnlj(Double sumnlj) {
        this.sumnlj = sumnlj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column well_daily_sum.Kzjsl
     *
     * @return the value of well_daily_sum.Kzjsl
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    public Integer getKzjsl() {
        return kzjsl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column well_daily_sum.Kzjsl
     *
     * @param kzjsl the value for well_daily_sum.Kzjsl
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    public void setKzjsl(Integer kzjsl) {
        this.kzjsl = kzjsl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column well_daily_sum.Kzjjh
     *
     * @return the value of well_daily_sum.Kzjjh
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    public String getKzjjh() {
        return kzjjh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column well_daily_sum.Kzjjh
     *
     * @param kzjjh the value for well_daily_sum.Kzjjh
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    public void setKzjjh(String kzjjh) {
        this.kzjjh = kzjjh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column well_daily_sum.Wzjsl
     *
     * @return the value of well_daily_sum.Wzjsl
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    public Integer getWzjsl() {
        return wzjsl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column well_daily_sum.Wzjsl
     *
     * @param wzjsl the value for well_daily_sum.Wzjsl
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    public void setWzjsl(Integer wzjsl) {
        this.wzjsl = wzjsl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column well_daily_sum.Wzjjh
     *
     * @return the value of well_daily_sum.Wzjjh
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    public String getWzjjh() {
        return wzjjh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column well_daily_sum.Wzjjh
     *
     * @param wzjjh the value for well_daily_sum.Wzjjh
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    public void setWzjjh(String wzjjh) {
        this.wzjjh = wzjjh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column well_daily_sum.Jjsl
     *
     * @return the value of well_daily_sum.Jjsl
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    public Integer getJjsl() {
        return jjsl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column well_daily_sum.Jjsl
     *
     * @param jjsl the value for well_daily_sum.Jjsl
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    public void setJjsl(Integer jjsl) {
        this.jjsl = jjsl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column well_daily_sum.Jjjh
     *
     * @return the value of well_daily_sum.Jjjh
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    public String getJjjh() {
        return jjjh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column well_daily_sum.Jjjh
     *
     * @param jjjh the value for well_daily_sum.Jjjh
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    public void setJjjh(String jjjh) {
        this.jjjh = jjjh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column well_daily_sum.CreateTime
     *
     * @return the value of well_daily_sum.CreateTime
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column well_daily_sum.CreateTime
     *
     * @param createtime the value for well_daily_sum.CreateTime
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column well_daily_sum.Zjdt
     *
     * @return the value of well_daily_sum.Zjdt
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    public Integer getZjdt() {
        return zjdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column well_daily_sum.Zjdt
     *
     * @param zjdt the value for well_daily_sum.Zjdt
     *
     * @mbggenerated Thu Aug 09 12:54:24 CST 2018
     */
    public void setZjdt(Integer zjdt) {
        this.zjdt = zjdt;
    }
}