package cn.caecc.erp.modules.dao.mybatis.mapper;

import cn.caecc.erp.modules.dao.mybatis.entity.VehicleActivitiApply;
import cn.caecc.erp.modules.dao.mybatis.entity.VehicleActivitiApplyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VehicleActivitiApplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle_activiti_apply
     *
     * @mbggenerated Tue Jun 26 13:44:52 CST 2018
     */
    int countByExample(VehicleActivitiApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle_activiti_apply
     *
     * @mbggenerated Tue Jun 26 13:44:52 CST 2018
     */
    int deleteByExample(VehicleActivitiApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle_activiti_apply
     *
     * @mbggenerated Tue Jun 26 13:44:52 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle_activiti_apply
     *
     * @mbggenerated Tue Jun 26 13:44:52 CST 2018
     */
    int insert(VehicleActivitiApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle_activiti_apply
     *
     * @mbggenerated Tue Jun 26 13:44:52 CST 2018
     */
    int insertSelective(VehicleActivitiApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle_activiti_apply
     *
     * @mbggenerated Tue Jun 26 13:44:52 CST 2018
     */
    List<VehicleActivitiApply> selectByExample(VehicleActivitiApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle_activiti_apply
     *
     * @mbggenerated Tue Jun 26 13:44:52 CST 2018
     */
    VehicleActivitiApply selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle_activiti_apply
     *
     * @mbggenerated Tue Jun 26 13:44:52 CST 2018
     */
    int updateByExampleSelective(@Param("record") VehicleActivitiApply record, @Param("example") VehicleActivitiApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle_activiti_apply
     *
     * @mbggenerated Tue Jun 26 13:44:52 CST 2018
     */
    int updateByExample(@Param("record") VehicleActivitiApply record, @Param("example") VehicleActivitiApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle_activiti_apply
     *
     * @mbggenerated Tue Jun 26 13:44:52 CST 2018
     */
    int updateByPrimaryKeySelective(VehicleActivitiApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle_activiti_apply
     *
     * @mbggenerated Tue Jun 26 13:44:52 CST 2018
     */
    int updateByPrimaryKey(VehicleActivitiApply record);
}