package com.bswebsite.modules.dao.mybatis.mapper;

import com.bswebsite.modules.dao.mybatis.entity.WellBit;
import com.bswebsite.modules.dao.mybatis.entity.WellBitExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WellBitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_bit
     *
     * @mbggenerated Tue Jun 19 16:30:41 CST 2018
     */
    int countByExample(WellBitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_bit
     *
     * @mbggenerated Tue Jun 19 16:30:41 CST 2018
     */
    int deleteByExample(WellBitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_bit
     *
     * @mbggenerated Tue Jun 19 16:30:41 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_bit
     *
     * @mbggenerated Tue Jun 19 16:30:41 CST 2018
     */
    int insert(WellBit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_bit
     *
     * @mbggenerated Tue Jun 19 16:30:41 CST 2018
     */
    int insertSelective(WellBit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_bit
     *
     * @mbggenerated Tue Jun 19 16:30:41 CST 2018
     */
    List<WellBit> selectByExample(WellBitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_bit
     *
     * @mbggenerated Tue Jun 19 16:30:41 CST 2018
     */
    WellBit selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_bit
     *
     * @mbggenerated Tue Jun 19 16:30:41 CST 2018
     */
    int updateByExampleSelective(@Param("record") WellBit record, @Param("example") WellBitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_bit
     *
     * @mbggenerated Tue Jun 19 16:30:41 CST 2018
     */
    int updateByExample(@Param("record") WellBit record, @Param("example") WellBitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_bit
     *
     * @mbggenerated Tue Jun 19 16:30:41 CST 2018
     */
    int updateByPrimaryKeySelective(WellBit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_bit
     *
     * @mbggenerated Tue Jun 19 16:30:41 CST 2018
     */
    int updateByPrimaryKey(WellBit record);
}