package com.bswebsite.modules.dao.mybatis.mapper;

import com.bswebsite.modules.dao.mybatis.entity.WellDxInfo;
import com.bswebsite.modules.dao.mybatis.entity.WellDxInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WellDxInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_dx_info
     *
     * @mbggenerated Tue Jun 19 16:30:41 CST 2018
     */
    int countByExample(WellDxInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_dx_info
     *
     * @mbggenerated Tue Jun 19 16:30:41 CST 2018
     */
    int deleteByExample(WellDxInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_dx_info
     *
     * @mbggenerated Tue Jun 19 16:30:41 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_dx_info
     *
     * @mbggenerated Tue Jun 19 16:30:41 CST 2018
     */
    int insert(WellDxInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_dx_info
     *
     * @mbggenerated Tue Jun 19 16:30:41 CST 2018
     */
    int insertSelective(WellDxInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_dx_info
     *
     * @mbggenerated Tue Jun 19 16:30:41 CST 2018
     */
    List<WellDxInfo> selectByExample(WellDxInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_dx_info
     *
     * @mbggenerated Tue Jun 19 16:30:41 CST 2018
     */
    WellDxInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_dx_info
     *
     * @mbggenerated Tue Jun 19 16:30:41 CST 2018
     */
    int updateByExampleSelective(@Param("record") WellDxInfo record, @Param("example") WellDxInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_dx_info
     *
     * @mbggenerated Tue Jun 19 16:30:41 CST 2018
     */
    int updateByExample(@Param("record") WellDxInfo record, @Param("example") WellDxInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_dx_info
     *
     * @mbggenerated Tue Jun 19 16:30:41 CST 2018
     */
    int updateByPrimaryKeySelective(WellDxInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_dx_info
     *
     * @mbggenerated Tue Jun 19 16:30:41 CST 2018
     */
    int updateByPrimaryKey(WellDxInfo record);
}