package com.bswebsite.modules.dao.mybatis.mapper;

import com.bswebsite.modules.dao.mybatis.entity.WellDxDaily;
import com.bswebsite.modules.dao.mybatis.entity.WellDxDailyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WellDxDailyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_dx_daily
     *
     * @mbggenerated Tue Jun 19 16:30:41 CST 2018
     */
    int countByExample(WellDxDailyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_dx_daily
     *
     * @mbggenerated Tue Jun 19 16:30:41 CST 2018
     */
    int deleteByExample(WellDxDailyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_dx_daily
     *
     * @mbggenerated Tue Jun 19 16:30:41 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_dx_daily
     *
     * @mbggenerated Tue Jun 19 16:30:41 CST 2018
     */
    int insert(WellDxDaily record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_dx_daily
     *
     * @mbggenerated Tue Jun 19 16:30:41 CST 2018
     */
    int insertSelective(WellDxDaily record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_dx_daily
     *
     * @mbggenerated Tue Jun 19 16:30:41 CST 2018
     */
    List<WellDxDaily> selectByExample(WellDxDailyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_dx_daily
     *
     * @mbggenerated Tue Jun 19 16:30:41 CST 2018
     */
    WellDxDaily selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_dx_daily
     *
     * @mbggenerated Tue Jun 19 16:30:41 CST 2018
     */
    int updateByExampleSelective(@Param("record") WellDxDaily record, @Param("example") WellDxDailyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_dx_daily
     *
     * @mbggenerated Tue Jun 19 16:30:41 CST 2018
     */
    int updateByExample(@Param("record") WellDxDaily record, @Param("example") WellDxDailyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_dx_daily
     *
     * @mbggenerated Tue Jun 19 16:30:41 CST 2018
     */
    int updateByPrimaryKeySelective(WellDxDaily record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_dx_daily
     *
     * @mbggenerated Tue Jun 19 16:30:41 CST 2018
     */
    int updateByPrimaryKey(WellDxDaily record);
}