package com.bswebsite.modules.dao.mybatis.mapper;

import com.bswebsite.modules.dao.mybatis.entity.WellXwDaily;
import com.bswebsite.modules.dao.mybatis.entity.WellXwDailyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WellXwDailyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_xw_daily
     *
     * @mbggenerated Tue Jun 19 16:30:41 CST 2018
     */
    int countByExample(WellXwDailyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_xw_daily
     *
     * @mbggenerated Tue Jun 19 16:30:41 CST 2018
     */
    int deleteByExample(WellXwDailyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_xw_daily
     *
     * @mbggenerated Tue Jun 19 16:30:41 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_xw_daily
     *
     * @mbggenerated Tue Jun 19 16:30:41 CST 2018
     */
    int insert(WellXwDaily record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_xw_daily
     *
     * @mbggenerated Tue Jun 19 16:30:41 CST 2018
     */
    int insertSelective(WellXwDaily record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_xw_daily
     *
     * @mbggenerated Tue Jun 19 16:30:41 CST 2018
     */
    List<WellXwDaily> selectByExample(WellXwDailyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_xw_daily
     *
     * @mbggenerated Tue Jun 19 16:30:41 CST 2018
     */
    WellXwDaily selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_xw_daily
     *
     * @mbggenerated Tue Jun 19 16:30:41 CST 2018
     */
    int updateByExampleSelective(@Param("record") WellXwDaily record, @Param("example") WellXwDailyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_xw_daily
     *
     * @mbggenerated Tue Jun 19 16:30:41 CST 2018
     */
    int updateByExample(@Param("record") WellXwDaily record, @Param("example") WellXwDailyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_xw_daily
     *
     * @mbggenerated Tue Jun 19 16:30:41 CST 2018
     */
    int updateByPrimaryKeySelective(WellXwDaily record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_xw_daily
     *
     * @mbggenerated Tue Jun 19 16:30:41 CST 2018
     */
    int updateByPrimaryKey(WellXwDaily record);
}