package com.bswebsite.modules.dao.mybatis.mapper;

import com.bswebsite.modules.dao.mybatis.entity.WellDaily;
import com.bswebsite.modules.dao.mybatis.entity.WellDailyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WellDailyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_daily_sum
     *
     * @mbggenerated Tue Jun 19 16:30:41 CST 2018
     */
    int countByExample(WellDailyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_daily_sum
     *
     * @mbggenerated Tue Jun 19 16:30:41 CST 2018
     */
    int deleteByExample(WellDailyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_daily_sum
     *
     * @mbggenerated Tue Jun 19 16:30:41 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_daily_sum
     *
     * @mbggenerated Tue Jun 19 16:30:41 CST 2018
     */
    int insert(WellDaily record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_daily_sum
     *
     * @mbggenerated Tue Jun 19 16:30:41 CST 2018
     */
    int insertSelective(WellDaily record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_daily_sum
     *
     * @mbggenerated Tue Jun 19 16:30:41 CST 2018
     */
    List<WellDaily> selectByExample(WellDailyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_daily_sum
     *
     * @mbggenerated Tue Jun 19 16:30:41 CST 2018
     */
    WellDaily selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_daily_sum
     *
     * @mbggenerated Tue Jun 19 16:30:41 CST 2018
     */
    int updateByExampleSelective(@Param("record") WellDaily record, @Param("example") WellDailyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_daily_sum
     *
     * @mbggenerated Tue Jun 19 16:30:41 CST 2018
     */
    int updateByExample(@Param("record") WellDaily record, @Param("example") WellDailyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_daily_sum
     *
     * @mbggenerated Tue Jun 19 16:30:41 CST 2018
     */
    int updateByPrimaryKeySelective(WellDaily record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_daily_sum
     *
     * @mbggenerated Tue Jun 19 16:30:41 CST 2018
     */
    int updateByPrimaryKey(WellDaily record);
}