package cn.caecc.erp.modules.dao.mybatis.mapper;

import cn.caecc.erp.modules.dao.mybatis.entity.DepartmentType;
import cn.caecc.erp.modules.dao.mybatis.entity.DepartmentTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DepartmentTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_type
     *
     * @mbggenerated Thu Jun 07 09:07:16 CST 2018
     */
    int countByExample(DepartmentTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_type
     *
     * @mbggenerated Thu Jun 07 09:07:16 CST 2018
     */
    int deleteByExample(DepartmentTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_type
     *
     * @mbggenerated Thu Jun 07 09:07:16 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_type
     *
     * @mbggenerated Thu Jun 07 09:07:16 CST 2018
     */
    int insert(DepartmentType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_type
     *
     * @mbggenerated Thu Jun 07 09:07:16 CST 2018
     */
    int insertSelective(DepartmentType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_type
     *
     * @mbggenerated Thu Jun 07 09:07:16 CST 2018
     */
    List<DepartmentType> selectByExample(DepartmentTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_type
     *
     * @mbggenerated Thu Jun 07 09:07:16 CST 2018
     */
    DepartmentType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_type
     *
     * @mbggenerated Thu Jun 07 09:07:16 CST 2018
     */
    int updateByExampleSelective(@Param("record") DepartmentType record, @Param("example") DepartmentTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_type
     *
     * @mbggenerated Thu Jun 07 09:07:16 CST 2018
     */
    int updateByExample(@Param("record") DepartmentType record, @Param("example") DepartmentTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_type
     *
     * @mbggenerated Thu Jun 07 09:07:16 CST 2018
     */
    int updateByPrimaryKeySelective(DepartmentType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_type
     *
     * @mbggenerated Thu Jun 07 09:07:16 CST 2018
     */
    int updateByPrimaryKey(DepartmentType record);
}