package cn.caecc.erp.modules.dao.mybatis.mapper;

import cn.caecc.erp.modules.dao.mybatis.entity.FixedassetsActivitiApply;
import cn.caecc.erp.modules.dao.mybatis.entity.FixedassetsActivitiApplyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FixedassetsActivitiApplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fixedassets_activiti_apply
     *
     * @mbggenerated Wed Aug 01 17:48:48 CST 2018
     */
    int countByExample(FixedassetsActivitiApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fixedassets_activiti_apply
     *
     * @mbggenerated Wed Aug 01 17:48:48 CST 2018
     */
    int deleteByExample(FixedassetsActivitiApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fixedassets_activiti_apply
     *
     * @mbggenerated Wed Aug 01 17:48:48 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fixedassets_activiti_apply
     *
     * @mbggenerated Wed Aug 01 17:48:48 CST 2018
     */
    int insert(FixedassetsActivitiApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fixedassets_activiti_apply
     *
     * @mbggenerated Wed Aug 01 17:48:48 CST 2018
     */
    int insertSelective(FixedassetsActivitiApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fixedassets_activiti_apply
     *
     * @mbggenerated Wed Aug 01 17:48:48 CST 2018
     */
    List<FixedassetsActivitiApply> selectByExample(FixedassetsActivitiApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fixedassets_activiti_apply
     *
     * @mbggenerated Wed Aug 01 17:48:48 CST 2018
     */
    FixedassetsActivitiApply selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fixedassets_activiti_apply
     *
     * @mbggenerated Wed Aug 01 17:48:48 CST 2018
     */
    int updateByExampleSelective(@Param("record") FixedassetsActivitiApply record, @Param("example") FixedassetsActivitiApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fixedassets_activiti_apply
     *
     * @mbggenerated Wed Aug 01 17:48:48 CST 2018
     */
    int updateByExample(@Param("record") FixedassetsActivitiApply record, @Param("example") FixedassetsActivitiApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fixedassets_activiti_apply
     *
     * @mbggenerated Wed Aug 01 17:48:48 CST 2018
     */
    int updateByPrimaryKeySelective(FixedassetsActivitiApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fixedassets_activiti_apply
     *
     * @mbggenerated Wed Aug 01 17:48:48 CST 2018
     */
    int updateByPrimaryKey(FixedassetsActivitiApply record);
}