package cn.caecc.erp.modules.dao.mybatis.mapper;

import cn.caecc.erp.modules.dao.mybatis.entity.OfficesupplyGoodsRelationshipActivitiApply;
import cn.caecc.erp.modules.dao.mybatis.entity.OfficesupplyGoodsRelationshipActivitiApplyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OfficesupplyGoodsRelationshipActivitiApplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table officesupply_goods_relationship_activiti_apply
     *
     * @mbggenerated Wed Aug 01 19:13:53 CST 2018
     */
    int countByExample(OfficesupplyGoodsRelationshipActivitiApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table officesupply_goods_relationship_activiti_apply
     *
     * @mbggenerated Wed Aug 01 19:13:53 CST 2018
     */
    int deleteByExample(OfficesupplyGoodsRelationshipActivitiApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table officesupply_goods_relationship_activiti_apply
     *
     * @mbggenerated Wed Aug 01 19:13:53 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table officesupply_goods_relationship_activiti_apply
     *
     * @mbggenerated Wed Aug 01 19:13:53 CST 2018
     */
    int insert(OfficesupplyGoodsRelationshipActivitiApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table officesupply_goods_relationship_activiti_apply
     *
     * @mbggenerated Wed Aug 01 19:13:53 CST 2018
     */
    int insertSelective(OfficesupplyGoodsRelationshipActivitiApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table officesupply_goods_relationship_activiti_apply
     *
     * @mbggenerated Wed Aug 01 19:13:53 CST 2018
     */
    List<OfficesupplyGoodsRelationshipActivitiApply> selectByExample(OfficesupplyGoodsRelationshipActivitiApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table officesupply_goods_relationship_activiti_apply
     *
     * @mbggenerated Wed Aug 01 19:13:53 CST 2018
     */
    OfficesupplyGoodsRelationshipActivitiApply selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table officesupply_goods_relationship_activiti_apply
     *
     * @mbggenerated Wed Aug 01 19:13:53 CST 2018
     */
    int updateByExampleSelective(@Param("record") OfficesupplyGoodsRelationshipActivitiApply record, @Param("example") OfficesupplyGoodsRelationshipActivitiApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table officesupply_goods_relationship_activiti_apply
     *
     * @mbggenerated Wed Aug 01 19:13:53 CST 2018
     */
    int updateByExample(@Param("record") OfficesupplyGoodsRelationshipActivitiApply record, @Param("example") OfficesupplyGoodsRelationshipActivitiApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table officesupply_goods_relationship_activiti_apply
     *
     * @mbggenerated Wed Aug 01 19:13:53 CST 2018
     */
    int updateByPrimaryKeySelective(OfficesupplyGoodsRelationshipActivitiApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table officesupply_goods_relationship_activiti_apply
     *
     * @mbggenerated Wed Aug 01 19:13:53 CST 2018
     */
    int updateByPrimaryKey(OfficesupplyGoodsRelationshipActivitiApply record);
}