package cn.caecc.erp.modules.dao.mybatis.mapper;

import cn.caecc.erp.modules.dao.mybatis.entity.ProjectActivitiApply;
import cn.caecc.erp.modules.dao.mybatis.entity.ProjectActivitiApplyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProjectActivitiApplyMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_activiti_apply
	 * @mbggenerated  Thu Aug 09 13:30:51 CST 2018
	 */
	int countByExample(ProjectActivitiApplyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_activiti_apply
	 * @mbggenerated  Thu Aug 09 13:30:51 CST 2018
	 */
	int deleteByExample(ProjectActivitiApplyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_activiti_apply
	 * @mbggenerated  Thu Aug 09 13:30:51 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_activiti_apply
	 * @mbggenerated  Thu Aug 09 13:30:51 CST 2018
	 */
	int insert(ProjectActivitiApply record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_activiti_apply
	 * @mbggenerated  Thu Aug 09 13:30:51 CST 2018
	 */
	int insertSelective(ProjectActivitiApply record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_activiti_apply
	 * @mbggenerated  Thu Aug 09 13:30:51 CST 2018
	 */
	List<ProjectActivitiApply> selectByExample(ProjectActivitiApplyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_activiti_apply
	 * @mbggenerated  Thu Aug 09 13:30:51 CST 2018
	 */
	ProjectActivitiApply selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_activiti_apply
	 * @mbggenerated  Thu Aug 09 13:30:51 CST 2018
	 */
	int updateByExampleSelective(@Param("record") ProjectActivitiApply record,
			@Param("example") ProjectActivitiApplyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_activiti_apply
	 * @mbggenerated  Thu Aug 09 13:30:51 CST 2018
	 */
	int updateByExample(@Param("record") ProjectActivitiApply record,
			@Param("example") ProjectActivitiApplyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_activiti_apply
	 * @mbggenerated  Thu Aug 09 13:30:51 CST 2018
	 */
	int updateByPrimaryKeySelective(ProjectActivitiApply record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_activiti_apply
	 * @mbggenerated  Thu Aug 09 13:30:51 CST 2018
	 */
	int updateByPrimaryKey(ProjectActivitiApply record);
}