package cn.caecc.erp.modules.dao.mybatis.mapper;

import cn.caecc.erp.modules.dao.mybatis.entity.WellWdQk;
import cn.caecc.erp.modules.dao.mybatis.entity.WellWdQkExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WellWdQkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_wd_qk
     *
     * @mbggenerated Mon Aug 13 09:32:01 CST 2018
     */
    int countByExample(WellWdQkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_wd_qk
     *
     * @mbggenerated Mon Aug 13 09:32:01 CST 2018
     */
    int deleteByExample(WellWdQkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_wd_qk
     *
     * @mbggenerated Mon Aug 13 09:32:01 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_wd_qk
     *
     * @mbggenerated Mon Aug 13 09:32:01 CST 2018
     */
    int insert(WellWdQk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_wd_qk
     *
     * @mbggenerated Mon Aug 13 09:32:01 CST 2018
     */
    int insertSelective(WellWdQk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_wd_qk
     *
     * @mbggenerated Mon Aug 13 09:32:01 CST 2018
     */
    List<WellWdQk> selectByExample(WellWdQkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_wd_qk
     *
     * @mbggenerated Mon Aug 13 09:32:01 CST 2018
     */
    WellWdQk selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_wd_qk
     *
     * @mbggenerated Mon Aug 13 09:32:01 CST 2018
     */
    int updateByExampleSelective(@Param("record") WellWdQk record, @Param("example") WellWdQkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_wd_qk
     *
     * @mbggenerated Mon Aug 13 09:32:01 CST 2018
     */
    int updateByExample(@Param("record") WellWdQk record, @Param("example") WellWdQkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_wd_qk
     *
     * @mbggenerated Mon Aug 13 09:32:01 CST 2018
     */
    int updateByPrimaryKeySelective(WellWdQk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_wd_qk
     *
     * @mbggenerated Mon Aug 13 09:32:01 CST 2018
     */
    int updateByPrimaryKey(WellWdQk record);
}