package cn.caecc.erp.modules.dao.mybatis.mapper;

import cn.caecc.erp.modules.dao.mybatis.entity.WellTime;
import cn.caecc.erp.modules.dao.mybatis.entity.WellTimeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WellTimeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_time
     *
     * @mbggenerated Thu Aug 09 11:27:31 CST 2018
     */
    int countByExample(WellTimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_time
     *
     * @mbggenerated Thu Aug 09 11:27:31 CST 2018
     */
    int deleteByExample(WellTimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_time
     *
     * @mbggenerated Thu Aug 09 11:27:31 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_time
     *
     * @mbggenerated Thu Aug 09 11:27:31 CST 2018
     */
    int insert(WellTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_time
     *
     * @mbggenerated Thu Aug 09 11:27:31 CST 2018
     */
    int insertSelective(WellTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_time
     *
     * @mbggenerated Thu Aug 09 11:27:31 CST 2018
     */
    List<WellTime> selectByExample(WellTimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_time
     *
     * @mbggenerated Thu Aug 09 11:27:31 CST 2018
     */
    WellTime selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_time
     *
     * @mbggenerated Thu Aug 09 11:27:31 CST 2018
     */
    int updateByExampleSelective(@Param("record") WellTime record, @Param("example") WellTimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_time
     *
     * @mbggenerated Thu Aug 09 11:27:31 CST 2018
     */
    int updateByExample(@Param("record") WellTime record, @Param("example") WellTimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_time
     *
     * @mbggenerated Thu Aug 09 11:27:31 CST 2018
     */
    int updateByPrimaryKeySelective(WellTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_time
     *
     * @mbggenerated Thu Aug 09 11:27:31 CST 2018
     */
    int updateByPrimaryKey(WellTime record);
}