package cn.caecc.erp.modules.dao.mybatis.mapper;

import cn.caecc.erp.modules.dao.mybatis.entity.WellWdDaily;
import cn.caecc.erp.modules.dao.mybatis.entity.WellWdDailyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WellWdDailyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_wd_daily
     *
     * @mbggenerated Tue Jun 26 17:52:59 CST 2018
     */
    int countByExample(WellWdDailyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_wd_daily
     *
     * @mbggenerated Tue Jun 26 17:52:59 CST 2018
     */
    int deleteByExample(WellWdDailyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_wd_daily
     *
     * @mbggenerated Tue Jun 26 17:52:59 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_wd_daily
     *
     * @mbggenerated Tue Jun 26 17:52:59 CST 2018
     */
    int insert(WellWdDaily record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_wd_daily
     *
     * @mbggenerated Tue Jun 26 17:52:59 CST 2018
     */
    int insertSelective(WellWdDaily record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_wd_daily
     *
     * @mbggenerated Tue Jun 26 17:52:59 CST 2018
     */
    List<WellWdDaily> selectByExample(WellWdDailyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_wd_daily
     *
     * @mbggenerated Tue Jun 26 17:52:59 CST 2018
     */
    WellWdDaily selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_wd_daily
     *
     * @mbggenerated Tue Jun 26 17:52:59 CST 2018
     */
    int updateByExampleSelective(@Param("record") WellWdDaily record, @Param("example") WellWdDailyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_wd_daily
     *
     * @mbggenerated Tue Jun 26 17:52:59 CST 2018
     */
    int updateByExample(@Param("record") WellWdDaily record, @Param("example") WellWdDailyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_wd_daily
     *
     * @mbggenerated Tue Jun 26 17:52:59 CST 2018
     */
    int updateByPrimaryKeySelective(WellWdDaily record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table well_wd_daily
     *
     * @mbggenerated Tue Jun 26 17:52:59 CST 2018
     */
    int updateByPrimaryKey(WellWdDaily record);
}