package cn.caecc.erp.modules.dao.mybatis.mapper;

import cn.caecc.erp.modules.dao.mybatis.entity.EventActivitiApply;
import cn.caecc.erp.modules.dao.mybatis.entity.EventActivitiApplyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EventActivitiApplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_activiti_apply
     *
     * @mbggenerated Fri Jul 06 08:53:42 CST 2018
     */
    int countByExample(EventActivitiApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_activiti_apply
     *
     * @mbggenerated Fri Jul 06 08:53:42 CST 2018
     */
    int deleteByExample(EventActivitiApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_activiti_apply
     *
     * @mbggenerated Fri Jul 06 08:53:42 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_activiti_apply
     *
     * @mbggenerated Fri Jul 06 08:53:42 CST 2018
     */
    int insert(EventActivitiApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_activiti_apply
     *
     * @mbggenerated Fri Jul 06 08:53:42 CST 2018
     */
    int insertSelective(EventActivitiApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_activiti_apply
     *
     * @mbggenerated Fri Jul 06 08:53:42 CST 2018
     */
    List<EventActivitiApply> selectByExample(EventActivitiApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_activiti_apply
     *
     * @mbggenerated Fri Jul 06 08:53:42 CST 2018
     */
    EventActivitiApply selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_activiti_apply
     *
     * @mbggenerated Fri Jul 06 08:53:42 CST 2018
     */
    int updateByExampleSelective(@Param("record") EventActivitiApply record, @Param("example") EventActivitiApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_activiti_apply
     *
     * @mbggenerated Fri Jul 06 08:53:42 CST 2018
     */
    int updateByExample(@Param("record") EventActivitiApply record, @Param("example") EventActivitiApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_activiti_apply
     *
     * @mbggenerated Fri Jul 06 08:53:42 CST 2018
     */
    int updateByPrimaryKeySelective(EventActivitiApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_activiti_apply
     *
     * @mbggenerated Fri Jul 06 08:53:42 CST 2018
     */
    int updateByPrimaryKey(EventActivitiApply record);
}