package cn.caecc.erp.modules.dao.mybatis.entity;

import java.io.Serializable;

public class ConferenceRoom implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conference_room.Id
     *
     * @mbggenerated Tue May 29 09:14:10 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conference_room.Name
     *
     * @mbggenerated Tue May 29 09:14:10 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conference_room.Address
     *
     * @mbggenerated Tue May 29 09:14:10 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conference_room.AccommodateNum
     *
     * @mbggenerated Tue May 29 09:14:10 CST 2018
     */
    private Integer accommodatenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table conference_room
     *
     * @mbggenerated Tue May 29 09:14:10 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conference_room.Id
     *
     * @return the value of conference_room.Id
     *
     * @mbggenerated Tue May 29 09:14:10 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conference_room.Id
     *
     * @param id the value for conference_room.Id
     *
     * @mbggenerated Tue May 29 09:14:10 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conference_room.Name
     *
     * @return the value of conference_room.Name
     *
     * @mbggenerated Tue May 29 09:14:10 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conference_room.Name
     *
     * @param name the value for conference_room.Name
     *
     * @mbggenerated Tue May 29 09:14:10 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conference_room.Address
     *
     * @return the value of conference_room.Address
     *
     * @mbggenerated Tue May 29 09:14:10 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conference_room.Address
     *
     * @param address the value for conference_room.Address
     *
     * @mbggenerated Tue May 29 09:14:10 CST 2018
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conference_room.AccommodateNum
     *
     * @return the value of conference_room.AccommodateNum
     *
     * @mbggenerated Tue May 29 09:14:10 CST 2018
     */
    public Integer getAccommodatenum() {
        return accommodatenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conference_room.AccommodateNum
     *
     * @param accommodatenum the value for conference_room.AccommodateNum
     *
     * @mbggenerated Tue May 29 09:14:10 CST 2018
     */
    public void setAccommodatenum(Integer accommodatenum) {
        this.accommodatenum = accommodatenum;
    }
}