package com.partymasses.modules.dao.mybatis.mapper;

import com.partymasses.modules.dao.mybatis.entity.QuestionType;
import com.partymasses.modules.dao.mybatis.entity.QuestionTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QuestionTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_type
     *
     * @mbggenerated Mon Apr 02 14:51:13 CST 2018
     */
    int countByExample(QuestionTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_type
     *
     * @mbggenerated Mon Apr 02 14:51:13 CST 2018
     */
    int deleteByExample(QuestionTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_type
     *
     * @mbggenerated Mon Apr 02 14:51:13 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_type
     *
     * @mbggenerated Mon Apr 02 14:51:13 CST 2018
     */
    int insert(QuestionType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_type
     *
     * @mbggenerated Mon Apr 02 14:51:13 CST 2018
     */
    int insertSelective(QuestionType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_type
     *
     * @mbggenerated Mon Apr 02 14:51:13 CST 2018
     */
    List<QuestionType> selectByExample(QuestionTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_type
     *
     * @mbggenerated Mon Apr 02 14:51:13 CST 2018
     */
    QuestionType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_type
     *
     * @mbggenerated Mon Apr 02 14:51:13 CST 2018
     */
    int updateByExampleSelective(@Param("record") QuestionType record, @Param("example") QuestionTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_type
     *
     * @mbggenerated Mon Apr 02 14:51:13 CST 2018
     */
    int updateByExample(@Param("record") QuestionType record, @Param("example") QuestionTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_type
     *
     * @mbggenerated Mon Apr 02 14:51:13 CST 2018
     */
    int updateByPrimaryKeySelective(QuestionType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_type
     *
     * @mbggenerated Mon Apr 02 14:51:13 CST 2018
     */
    int updateByPrimaryKey(QuestionType record);
}