package cn.caecc.erp.modules.dao.mybatis.mapper;

import cn.caecc.erp.modules.dao.mybatis.entity.DispatchActivitiApply;
import cn.caecc.erp.modules.dao.mybatis.entity.DispatchActivitiApplyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DispatchActivitiApplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dispatch_activiti_apply
     *
     * @mbggenerated Fri Jul 13 15:48:20 CST 2018
     */
    int countByExample(DispatchActivitiApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dispatch_activiti_apply
     *
     * @mbggenerated Fri Jul 13 15:48:20 CST 2018
     */
    int deleteByExample(DispatchActivitiApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dispatch_activiti_apply
     *
     * @mbggenerated Fri Jul 13 15:48:20 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dispatch_activiti_apply
     *
     * @mbggenerated Fri Jul 13 15:48:20 CST 2018
     */
    int insert(DispatchActivitiApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dispatch_activiti_apply
     *
     * @mbggenerated Fri Jul 13 15:48:20 CST 2018
     */
    int insertSelective(DispatchActivitiApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dispatch_activiti_apply
     *
     * @mbggenerated Fri Jul 13 15:48:20 CST 2018
     */
    List<DispatchActivitiApply> selectByExampleWithBLOBs(DispatchActivitiApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dispatch_activiti_apply
     *
     * @mbggenerated Fri Jul 13 15:48:20 CST 2018
     */
    List<DispatchActivitiApply> selectByExample(DispatchActivitiApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dispatch_activiti_apply
     *
     * @mbggenerated Fri Jul 13 15:48:20 CST 2018
     */
    DispatchActivitiApply selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dispatch_activiti_apply
     *
     * @mbggenerated Fri Jul 13 15:48:20 CST 2018
     */
    int updateByExampleSelective(@Param("record") DispatchActivitiApply record, @Param("example") DispatchActivitiApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dispatch_activiti_apply
     *
     * @mbggenerated Fri Jul 13 15:48:20 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") DispatchActivitiApply record, @Param("example") DispatchActivitiApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dispatch_activiti_apply
     *
     * @mbggenerated Fri Jul 13 15:48:20 CST 2018
     */
    int updateByExample(@Param("record") DispatchActivitiApply record, @Param("example") DispatchActivitiApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dispatch_activiti_apply
     *
     * @mbggenerated Fri Jul 13 15:48:20 CST 2018
     */
    int updateByPrimaryKeySelective(DispatchActivitiApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dispatch_activiti_apply
     *
     * @mbggenerated Fri Jul 13 15:48:20 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(DispatchActivitiApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dispatch_activiti_apply
     *
     * @mbggenerated Fri Jul 13 15:48:20 CST 2018
     */
    int updateByPrimaryKey(DispatchActivitiApply record);
}