package cn.caecc.erp.modules.dao.mybatis.entity;

import java.io.Serializable;
import java.util.Date;

public class VehicleActivitiApply implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle_activiti_apply.Id
     *
     * @mbggenerated Tue Jun 26 13:44:52 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle_activiti_apply.ProcessInstanceId
     *
     * @mbggenerated Tue Jun 26 13:44:52 CST 2018
     */
    private String processinstanceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle_activiti_apply.UId
     *
     * @mbggenerated Tue Jun 26 13:44:52 CST 2018
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle_activiti_apply.DId
     *
     * @mbggenerated Tue Jun 26 13:44:52 CST 2018
     */
    private Integer did;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle_activiti_apply.Address
     *
     * @mbggenerated Tue Jun 26 13:44:52 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle_activiti_apply.NumberOfPepole
     *
     * @mbggenerated Tue Jun 26 13:44:52 CST 2018
     */
    private Integer numberofpepole;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle_activiti_apply.PlanTime
     *
     * @mbggenerated Tue Jun 26 13:44:52 CST 2018
     */
    private Date plantime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle_activiti_apply.NumberOfHours
     *
     * @mbggenerated Tue Jun 26 13:44:52 CST 2018
     */
    private Integer numberofhours;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle_activiti_apply.Cause
     *
     * @mbggenerated Tue Jun 26 13:44:52 CST 2018
     */
    private String cause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle_activiti_apply.PlannedRoute
     *
     * @mbggenerated Tue Jun 26 13:44:52 CST 2018
     */
    private String plannedroute;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle_activiti_apply.ReMark
     *
     * @mbggenerated Tue Jun 26 13:44:52 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle_activiti_apply.CreateUserId
     *
     * @mbggenerated Tue Jun 26 13:44:52 CST 2018
     */
    private Integer createuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle_activiti_apply.Createtime
     *
     * @mbggenerated Tue Jun 26 13:44:52 CST 2018
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle_activiti_apply.IsSuccess
     *
     * @mbggenerated Tue Jun 26 13:44:52 CST 2018
     */
    private Integer issuccess;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vehicle_activiti_apply
     *
     * @mbggenerated Tue Jun 26 13:44:52 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle_activiti_apply.Id
     *
     * @return the value of vehicle_activiti_apply.Id
     *
     * @mbggenerated Tue Jun 26 13:44:52 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle_activiti_apply.Id
     *
     * @param id the value for vehicle_activiti_apply.Id
     *
     * @mbggenerated Tue Jun 26 13:44:52 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle_activiti_apply.ProcessInstanceId
     *
     * @return the value of vehicle_activiti_apply.ProcessInstanceId
     *
     * @mbggenerated Tue Jun 26 13:44:52 CST 2018
     */
    public String getProcessinstanceid() {
        return processinstanceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle_activiti_apply.ProcessInstanceId
     *
     * @param processinstanceid the value for vehicle_activiti_apply.ProcessInstanceId
     *
     * @mbggenerated Tue Jun 26 13:44:52 CST 2018
     */
    public void setProcessinstanceid(String processinstanceid) {
        this.processinstanceid = processinstanceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle_activiti_apply.UId
     *
     * @return the value of vehicle_activiti_apply.UId
     *
     * @mbggenerated Tue Jun 26 13:44:52 CST 2018
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle_activiti_apply.UId
     *
     * @param uid the value for vehicle_activiti_apply.UId
     *
     * @mbggenerated Tue Jun 26 13:44:52 CST 2018
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle_activiti_apply.DId
     *
     * @return the value of vehicle_activiti_apply.DId
     *
     * @mbggenerated Tue Jun 26 13:44:52 CST 2018
     */
    public Integer getDid() {
        return did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle_activiti_apply.DId
     *
     * @param did the value for vehicle_activiti_apply.DId
     *
     * @mbggenerated Tue Jun 26 13:44:52 CST 2018
     */
    public void setDid(Integer did) {
        this.did = did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle_activiti_apply.Address
     *
     * @return the value of vehicle_activiti_apply.Address
     *
     * @mbggenerated Tue Jun 26 13:44:52 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle_activiti_apply.Address
     *
     * @param address the value for vehicle_activiti_apply.Address
     *
     * @mbggenerated Tue Jun 26 13:44:52 CST 2018
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle_activiti_apply.NumberOfPepole
     *
     * @return the value of vehicle_activiti_apply.NumberOfPepole
     *
     * @mbggenerated Tue Jun 26 13:44:52 CST 2018
     */
    public Integer getNumberofpepole() {
        return numberofpepole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle_activiti_apply.NumberOfPepole
     *
     * @param numberofpepole the value for vehicle_activiti_apply.NumberOfPepole
     *
     * @mbggenerated Tue Jun 26 13:44:52 CST 2018
     */
    public void setNumberofpepole(Integer numberofpepole) {
        this.numberofpepole = numberofpepole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle_activiti_apply.PlanTime
     *
     * @return the value of vehicle_activiti_apply.PlanTime
     *
     * @mbggenerated Tue Jun 26 13:44:52 CST 2018
     */
    public Date getPlantime() {
        return plantime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle_activiti_apply.PlanTime
     *
     * @param plantime the value for vehicle_activiti_apply.PlanTime
     *
     * @mbggenerated Tue Jun 26 13:44:52 CST 2018
     */
    public void setPlantime(Date plantime) {
        this.plantime = plantime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle_activiti_apply.NumberOfHours
     *
     * @return the value of vehicle_activiti_apply.NumberOfHours
     *
     * @mbggenerated Tue Jun 26 13:44:52 CST 2018
     */
    public Integer getNumberofhours() {
        return numberofhours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle_activiti_apply.NumberOfHours
     *
     * @param numberofhours the value for vehicle_activiti_apply.NumberOfHours
     *
     * @mbggenerated Tue Jun 26 13:44:52 CST 2018
     */
    public void setNumberofhours(Integer numberofhours) {
        this.numberofhours = numberofhours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle_activiti_apply.Cause
     *
     * @return the value of vehicle_activiti_apply.Cause
     *
     * @mbggenerated Tue Jun 26 13:44:52 CST 2018
     */
    public String getCause() {
        return cause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle_activiti_apply.Cause
     *
     * @param cause the value for vehicle_activiti_apply.Cause
     *
     * @mbggenerated Tue Jun 26 13:44:52 CST 2018
     */
    public void setCause(String cause) {
        this.cause = cause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle_activiti_apply.PlannedRoute
     *
     * @return the value of vehicle_activiti_apply.PlannedRoute
     *
     * @mbggenerated Tue Jun 26 13:44:52 CST 2018
     */
    public String getPlannedroute() {
        return plannedroute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle_activiti_apply.PlannedRoute
     *
     * @param plannedroute the value for vehicle_activiti_apply.PlannedRoute
     *
     * @mbggenerated Tue Jun 26 13:44:52 CST 2018
     */
    public void setPlannedroute(String plannedroute) {
        this.plannedroute = plannedroute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle_activiti_apply.ReMark
     *
     * @return the value of vehicle_activiti_apply.ReMark
     *
     * @mbggenerated Tue Jun 26 13:44:52 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle_activiti_apply.ReMark
     *
     * @param remark the value for vehicle_activiti_apply.ReMark
     *
     * @mbggenerated Tue Jun 26 13:44:52 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle_activiti_apply.CreateUserId
     *
     * @return the value of vehicle_activiti_apply.CreateUserId
     *
     * @mbggenerated Tue Jun 26 13:44:52 CST 2018
     */
    public Integer getCreateuserid() {
        return createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle_activiti_apply.CreateUserId
     *
     * @param createuserid the value for vehicle_activiti_apply.CreateUserId
     *
     * @mbggenerated Tue Jun 26 13:44:52 CST 2018
     */
    public void setCreateuserid(Integer createuserid) {
        this.createuserid = createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle_activiti_apply.Createtime
     *
     * @return the value of vehicle_activiti_apply.Createtime
     *
     * @mbggenerated Tue Jun 26 13:44:52 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle_activiti_apply.Createtime
     *
     * @param createtime the value for vehicle_activiti_apply.Createtime
     *
     * @mbggenerated Tue Jun 26 13:44:52 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle_activiti_apply.IsSuccess
     *
     * @return the value of vehicle_activiti_apply.IsSuccess
     *
     * @mbggenerated Tue Jun 26 13:44:52 CST 2018
     */
    public Integer getIssuccess() {
        return issuccess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle_activiti_apply.IsSuccess
     *
     * @param issuccess the value for vehicle_activiti_apply.IsSuccess
     *
     * @mbggenerated Tue Jun 26 13:44:52 CST 2018
     */
    public void setIssuccess(Integer issuccess) {
        this.issuccess = issuccess;
    }
}