package cn.caecc.erp.modules.dao.mybatis.entity;

import java.io.Serializable;

public class DepartmentType implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department_type.Id
     *
     * @mbggenerated Thu Jun 07 09:07:16 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department_type.Name
     *
     * @mbggenerated Thu Jun 07 09:07:16 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table department_type
     *
     * @mbggenerated Thu Jun 07 09:07:16 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department_type.Id
     *
     * @return the value of department_type.Id
     *
     * @mbggenerated Thu Jun 07 09:07:16 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department_type.Id
     *
     * @param id the value for department_type.Id
     *
     * @mbggenerated Thu Jun 07 09:07:16 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department_type.Name
     *
     * @return the value of department_type.Name
     *
     * @mbggenerated Thu Jun 07 09:07:16 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department_type.Name
     *
     * @param name the value for department_type.Name
     *
     * @mbggenerated Thu Jun 07 09:07:16 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }
}