package com.partymasses.modules.dao.mybatis.entity;

public class ActivityUnits {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_units.Id
     *
     * @mbggenerated Tue Mar 27 09:01:40 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_units.AtvId
     *
     * @mbggenerated Tue Mar 27 09:01:40 CST 2018
     */
    private Integer atvid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_units.UnitId
     *
     * @mbggenerated Tue Mar 27 09:01:40 CST 2018
     */
    private Integer unitid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_units.Id
     *
     * @return the value of activity_units.Id
     *
     * @mbggenerated Tue Mar 27 09:01:40 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_units.Id
     *
     * @param id the value for activity_units.Id
     *
     * @mbggenerated Tue Mar 27 09:01:40 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_units.AtvId
     *
     * @return the value of activity_units.AtvId
     *
     * @mbggenerated Tue Mar 27 09:01:40 CST 2018
     */
    public Integer getAtvid() {
        return atvid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_units.AtvId
     *
     * @param atvid the value for activity_units.AtvId
     *
     * @mbggenerated Tue Mar 27 09:01:40 CST 2018
     */
    public void setAtvid(Integer atvid) {
        this.atvid = atvid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_units.UnitId
     *
     * @return the value of activity_units.UnitId
     *
     * @mbggenerated Tue Mar 27 09:01:40 CST 2018
     */
    public Integer getUnitid() {
        return unitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_units.UnitId
     *
     * @param unitid the value for activity_units.UnitId
     *
     * @mbggenerated Tue Mar 27 09:01:40 CST 2018
     */
    public void setUnitid(Integer unitid) {
        this.unitid = unitid;
    }
}