package com.partymasses.modules.dao.mybatis.entity;

import java.util.Date;

public class Test {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.Id
     *
     * @mbggenerated Thu Mar 29 09:47:41 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.Name
     *
     * @mbggenerated Thu Mar 29 09:47:41 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.CreateTime
     *
     * @mbggenerated Thu Mar 29 09:47:41 CST 2018
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.CreateUser
     *
     * @mbggenerated Thu Mar 29 09:47:41 CST 2018
     */
    private Integer createuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.UpdateTime
     *
     * @mbggenerated Thu Mar 29 09:47:41 CST 2018
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.UpdateUser
     *
     * @mbggenerated Thu Mar 29 09:47:41 CST 2018
     */
    private Integer updateuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.TestTime
     *
     * @mbggenerated Thu Mar 29 09:47:41 CST 2018
     */
    private Integer testtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.UnitId
     *
     * @mbggenerated Thu Mar 29 09:47:41 CST 2018
     */
    private Integer unitid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.TotalScore
     *
     * @mbggenerated Thu Mar 29 09:47:41 CST 2018
     */
    private Integer totalscore;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.Id
     *
     * @return the value of test.Id
     *
     * @mbggenerated Thu Mar 29 09:47:41 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.Id
     *
     * @param id the value for test.Id
     *
     * @mbggenerated Thu Mar 29 09:47:41 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.Name
     *
     * @return the value of test.Name
     *
     * @mbggenerated Thu Mar 29 09:47:41 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.Name
     *
     * @param name the value for test.Name
     *
     * @mbggenerated Thu Mar 29 09:47:41 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.CreateTime
     *
     * @return the value of test.CreateTime
     *
     * @mbggenerated Thu Mar 29 09:47:41 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.CreateTime
     *
     * @param createtime the value for test.CreateTime
     *
     * @mbggenerated Thu Mar 29 09:47:41 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.CreateUser
     *
     * @return the value of test.CreateUser
     *
     * @mbggenerated Thu Mar 29 09:47:41 CST 2018
     */
    public Integer getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.CreateUser
     *
     * @param createuser the value for test.CreateUser
     *
     * @mbggenerated Thu Mar 29 09:47:41 CST 2018
     */
    public void setCreateuser(Integer createuser) {
        this.createuser = createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.UpdateTime
     *
     * @return the value of test.UpdateTime
     *
     * @mbggenerated Thu Mar 29 09:47:41 CST 2018
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.UpdateTime
     *
     * @param updatetime the value for test.UpdateTime
     *
     * @mbggenerated Thu Mar 29 09:47:41 CST 2018
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.UpdateUser
     *
     * @return the value of test.UpdateUser
     *
     * @mbggenerated Thu Mar 29 09:47:41 CST 2018
     */
    public Integer getUpdateuser() {
        return updateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.UpdateUser
     *
     * @param updateuser the value for test.UpdateUser
     *
     * @mbggenerated Thu Mar 29 09:47:41 CST 2018
     */
    public void setUpdateuser(Integer updateuser) {
        this.updateuser = updateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.TestTime
     *
     * @return the value of test.TestTime
     *
     * @mbggenerated Thu Mar 29 09:47:41 CST 2018
     */
    public Integer getTesttime() {
        return testtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.TestTime
     *
     * @param testtime the value for test.TestTime
     *
     * @mbggenerated Thu Mar 29 09:47:41 CST 2018
     */
    public void setTesttime(Integer testtime) {
        this.testtime = testtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.UnitId
     *
     * @return the value of test.UnitId
     *
     * @mbggenerated Thu Mar 29 09:47:41 CST 2018
     */
    public Integer getUnitid() {
        return unitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.UnitId
     *
     * @param unitid the value for test.UnitId
     *
     * @mbggenerated Thu Mar 29 09:47:41 CST 2018
     */
    public void setUnitid(Integer unitid) {
        this.unitid = unitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.TotalScore
     *
     * @return the value of test.TotalScore
     *
     * @mbggenerated Thu Mar 29 09:47:41 CST 2018
     */
    public Integer getTotalscore() {
        return totalscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.TotalScore
     *
     * @param totalscore the value for test.TotalScore
     *
     * @mbggenerated Thu Mar 29 09:47:41 CST 2018
     */
    public void setTotalscore(Integer totalscore) {
        this.totalscore = totalscore;
    }
}