package com.partymasses.modules.dao.mybatis.entity;

import java.util.Date;

public class Video {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.Id
     *
     * @mbggenerated Sun Apr 08 10:58:02 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.Name
     *
     * @mbggenerated Sun Apr 08 10:58:02 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.Size
     *
     * @mbggenerated Sun Apr 08 10:58:02 CST 2018
     */
    private String size;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.VideoPath
     *
     * @mbggenerated Sun Apr 08 10:58:02 CST 2018
     */
    private String videopath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.ThumbnailPath
     *
     * @mbggenerated Sun Apr 08 10:58:02 CST 2018
     */
    private String thumbnailpath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.TypeId
     *
     * @mbggenerated Sun Apr 08 10:58:02 CST 2018
     */
    private Integer typeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.UnitId
     *
     * @mbggenerated Sun Apr 08 10:58:02 CST 2018
     */
    private Integer unitid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.CreateUser
     *
     * @mbggenerated Sun Apr 08 10:58:02 CST 2018
     */
    private String createuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.CreateTime
     *
     * @mbggenerated Sun Apr 08 10:58:02 CST 2018
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.UpdateUser
     *
     * @mbggenerated Sun Apr 08 10:58:02 CST 2018
     */
    private String updateuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.UpdateTime
     *
     * @mbggenerated Sun Apr 08 10:58:02 CST 2018
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.Description
     *
     * @mbggenerated Sun Apr 08 10:58:02 CST 2018
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.IsSuccess
     *
     * @mbggenerated Sun Apr 08 10:58:02 CST 2018
     */
    private Integer issuccess;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.Id
     *
     * @return the value of video.Id
     *
     * @mbggenerated Sun Apr 08 10:58:02 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.Id
     *
     * @param id the value for video.Id
     *
     * @mbggenerated Sun Apr 08 10:58:02 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.Name
     *
     * @return the value of video.Name
     *
     * @mbggenerated Sun Apr 08 10:58:02 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.Name
     *
     * @param name the value for video.Name
     *
     * @mbggenerated Sun Apr 08 10:58:02 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.Size
     *
     * @return the value of video.Size
     *
     * @mbggenerated Sun Apr 08 10:58:02 CST 2018
     */
    public String getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.Size
     *
     * @param size the value for video.Size
     *
     * @mbggenerated Sun Apr 08 10:58:02 CST 2018
     */
    public void setSize(String size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.VideoPath
     *
     * @return the value of video.VideoPath
     *
     * @mbggenerated Sun Apr 08 10:58:02 CST 2018
     */
    public String getVideopath() {
        return videopath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.VideoPath
     *
     * @param videopath the value for video.VideoPath
     *
     * @mbggenerated Sun Apr 08 10:58:02 CST 2018
     */
    public void setVideopath(String videopath) {
        this.videopath = videopath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.ThumbnailPath
     *
     * @return the value of video.ThumbnailPath
     *
     * @mbggenerated Sun Apr 08 10:58:02 CST 2018
     */
    public String getThumbnailpath() {
        return thumbnailpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.ThumbnailPath
     *
     * @param thumbnailpath the value for video.ThumbnailPath
     *
     * @mbggenerated Sun Apr 08 10:58:02 CST 2018
     */
    public void setThumbnailpath(String thumbnailpath) {
        this.thumbnailpath = thumbnailpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.TypeId
     *
     * @return the value of video.TypeId
     *
     * @mbggenerated Sun Apr 08 10:58:02 CST 2018
     */
    public Integer getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.TypeId
     *
     * @param typeid the value for video.TypeId
     *
     * @mbggenerated Sun Apr 08 10:58:02 CST 2018
     */
    public void setTypeid(Integer typeid) {
        this.typeid = typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.UnitId
     *
     * @return the value of video.UnitId
     *
     * @mbggenerated Sun Apr 08 10:58:02 CST 2018
     */
    public Integer getUnitid() {
        return unitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.UnitId
     *
     * @param unitid the value for video.UnitId
     *
     * @mbggenerated Sun Apr 08 10:58:02 CST 2018
     */
    public void setUnitid(Integer unitid) {
        this.unitid = unitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.CreateUser
     *
     * @return the value of video.CreateUser
     *
     * @mbggenerated Sun Apr 08 10:58:02 CST 2018
     */
    public String getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.CreateUser
     *
     * @param createuser the value for video.CreateUser
     *
     * @mbggenerated Sun Apr 08 10:58:02 CST 2018
     */
    public void setCreateuser(String createuser) {
        this.createuser = createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.CreateTime
     *
     * @return the value of video.CreateTime
     *
     * @mbggenerated Sun Apr 08 10:58:02 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.CreateTime
     *
     * @param createtime the value for video.CreateTime
     *
     * @mbggenerated Sun Apr 08 10:58:02 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.UpdateUser
     *
     * @return the value of video.UpdateUser
     *
     * @mbggenerated Sun Apr 08 10:58:02 CST 2018
     */
    public String getUpdateuser() {
        return updateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.UpdateUser
     *
     * @param updateuser the value for video.UpdateUser
     *
     * @mbggenerated Sun Apr 08 10:58:02 CST 2018
     */
    public void setUpdateuser(String updateuser) {
        this.updateuser = updateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.UpdateTime
     *
     * @return the value of video.UpdateTime
     *
     * @mbggenerated Sun Apr 08 10:58:02 CST 2018
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.UpdateTime
     *
     * @param updatetime the value for video.UpdateTime
     *
     * @mbggenerated Sun Apr 08 10:58:02 CST 2018
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.Description
     *
     * @return the value of video.Description
     *
     * @mbggenerated Sun Apr 08 10:58:02 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.Description
     *
     * @param description the value for video.Description
     *
     * @mbggenerated Sun Apr 08 10:58:02 CST 2018
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.IsSuccess
     *
     * @return the value of video.IsSuccess
     *
     * @mbggenerated Sun Apr 08 10:58:02 CST 2018
     */
    public Integer getIssuccess() {
        return issuccess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.IsSuccess
     *
     * @param issuccess the value for video.IsSuccess
     *
     * @mbggenerated Sun Apr 08 10:58:02 CST 2018
     */
    public void setIssuccess(Integer issuccess) {
        this.issuccess = issuccess;
    }
}