package cn.caecc.erp.modules.dao.mybatis.mapper;

import cn.caecc.erp.modules.dao.mybatis.entity.SupplierGoodsRelationship;
import cn.caecc.erp.modules.dao.mybatis.entity.SupplierGoodsRelationshipExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SupplierGoodsRelationshipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_goods_relationship
     *
     * @mbggenerated Wed Aug 15 13:52:14 CST 2018
     */
    int countByExample(SupplierGoodsRelationshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_goods_relationship
     *
     * @mbggenerated Wed Aug 15 13:52:14 CST 2018
     */
    int deleteByExample(SupplierGoodsRelationshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_goods_relationship
     *
     * @mbggenerated Wed Aug 15 13:52:14 CST 2018
     */
    int insert(SupplierGoodsRelationship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_goods_relationship
     *
     * @mbggenerated Wed Aug 15 13:52:14 CST 2018
     */
    int insertSelective(SupplierGoodsRelationship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_goods_relationship
     *
     * @mbggenerated Wed Aug 15 13:52:14 CST 2018
     */
    List<SupplierGoodsRelationship> selectByExample(SupplierGoodsRelationshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_goods_relationship
     *
     * @mbggenerated Wed Aug 15 13:52:14 CST 2018
     */
    int updateByExampleSelective(@Param("record") SupplierGoodsRelationship record, @Param("example") SupplierGoodsRelationshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_goods_relationship
     *
     * @mbggenerated Wed Aug 15 13:52:14 CST 2018
     */
    int updateByExample(@Param("record") SupplierGoodsRelationship record, @Param("example") SupplierGoodsRelationshipExample example);
}