package cn.caecc.erp.modules.dao.mybatis.entity;

import java.io.Serializable;

public class DepartmentRoleRelationshipKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department_role_relationship.DId
     *
     * @mbggenerated Wed Jun 06 11:10:36 CST 2018
     */
    private Integer did;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department_role_relationship.RId
     *
     * @mbggenerated Wed Jun 06 11:10:36 CST 2018
     */
    private Integer rid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table department_role_relationship
     *
     * @mbggenerated Wed Jun 06 11:10:36 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department_role_relationship.DId
     *
     * @return the value of department_role_relationship.DId
     *
     * @mbggenerated Wed Jun 06 11:10:36 CST 2018
     */
    public Integer getDid() {
        return did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department_role_relationship.DId
     *
     * @param did the value for department_role_relationship.DId
     *
     * @mbggenerated Wed Jun 06 11:10:36 CST 2018
     */
    public void setDid(Integer did) {
        this.did = did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department_role_relationship.RId
     *
     * @return the value of department_role_relationship.RId
     *
     * @mbggenerated Wed Jun 06 11:10:36 CST 2018
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department_role_relationship.RId
     *
     * @param rid the value for department_role_relationship.RId
     *
     * @mbggenerated Wed Jun 06 11:10:36 CST 2018
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }
}