package cn.caecc.erp.modules.dao.mybatis.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ProjectActivitiApplyExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table project_activiti_apply
	 * @mbggenerated  Thu Aug 09 13:30:51 CST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table project_activiti_apply
	 * @mbggenerated  Thu Aug 09 13:30:51 CST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table project_activiti_apply
	 * @mbggenerated  Thu Aug 09 13:30:51 CST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_activiti_apply
	 * @mbggenerated  Thu Aug 09 13:30:51 CST 2018
	 */
	public ProjectActivitiApplyExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_activiti_apply
	 * @mbggenerated  Thu Aug 09 13:30:51 CST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_activiti_apply
	 * @mbggenerated  Thu Aug 09 13:30:51 CST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_activiti_apply
	 * @mbggenerated  Thu Aug 09 13:30:51 CST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_activiti_apply
	 * @mbggenerated  Thu Aug 09 13:30:51 CST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_activiti_apply
	 * @mbggenerated  Thu Aug 09 13:30:51 CST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_activiti_apply
	 * @mbggenerated  Thu Aug 09 13:30:51 CST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_activiti_apply
	 * @mbggenerated  Thu Aug 09 13:30:51 CST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_activiti_apply
	 * @mbggenerated  Thu Aug 09 13:30:51 CST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_activiti_apply
	 * @mbggenerated  Thu Aug 09 13:30:51 CST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_activiti_apply
	 * @mbggenerated  Thu Aug 09 13:30:51 CST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table project_activiti_apply
	 * @mbggenerated  Thu Aug 09 13:30:51 CST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("Id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("Id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("Id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("Id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("Id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("Id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("Id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("Id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("Id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("Id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("Id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("Id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andCodeIsNull() {
			addCriterion("Code is null");
			return (Criteria) this;
		}

		public Criteria andCodeIsNotNull() {
			addCriterion("Code is not null");
			return (Criteria) this;
		}

		public Criteria andCodeEqualTo(String value) {
			addCriterion("Code =", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotEqualTo(String value) {
			addCriterion("Code <>", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeGreaterThan(String value) {
			addCriterion("Code >", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeGreaterThanOrEqualTo(String value) {
			addCriterion("Code >=", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLessThan(String value) {
			addCriterion("Code <", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLessThanOrEqualTo(String value) {
			addCriterion("Code <=", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLike(String value) {
			addCriterion("Code like", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotLike(String value) {
			addCriterion("Code not like", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeIn(List<String> values) {
			addCriterion("Code in", values, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotIn(List<String> values) {
			addCriterion("Code not in", values, "code");
			return (Criteria) this;
		}

		public Criteria andCodeBetween(String value1, String value2) {
			addCriterion("Code between", value1, value2, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotBetween(String value1, String value2) {
			addCriterion("Code not between", value1, value2, "code");
			return (Criteria) this;
		}

		public Criteria andProcessinstanceidIsNull() {
			addCriterion("ProcessInstanceId is null");
			return (Criteria) this;
		}

		public Criteria andProcessinstanceidIsNotNull() {
			addCriterion("ProcessInstanceId is not null");
			return (Criteria) this;
		}

		public Criteria andProcessinstanceidEqualTo(String value) {
			addCriterion("ProcessInstanceId =", value, "processinstanceid");
			return (Criteria) this;
		}

		public Criteria andProcessinstanceidNotEqualTo(String value) {
			addCriterion("ProcessInstanceId <>", value, "processinstanceid");
			return (Criteria) this;
		}

		public Criteria andProcessinstanceidGreaterThan(String value) {
			addCriterion("ProcessInstanceId >", value, "processinstanceid");
			return (Criteria) this;
		}

		public Criteria andProcessinstanceidGreaterThanOrEqualTo(String value) {
			addCriterion("ProcessInstanceId >=", value, "processinstanceid");
			return (Criteria) this;
		}

		public Criteria andProcessinstanceidLessThan(String value) {
			addCriterion("ProcessInstanceId <", value, "processinstanceid");
			return (Criteria) this;
		}

		public Criteria andProcessinstanceidLessThanOrEqualTo(String value) {
			addCriterion("ProcessInstanceId <=", value, "processinstanceid");
			return (Criteria) this;
		}

		public Criteria andProcessinstanceidLike(String value) {
			addCriterion("ProcessInstanceId like", value, "processinstanceid");
			return (Criteria) this;
		}

		public Criteria andProcessinstanceidNotLike(String value) {
			addCriterion("ProcessInstanceId not like", value, "processinstanceid");
			return (Criteria) this;
		}

		public Criteria andProcessinstanceidIn(List<String> values) {
			addCriterion("ProcessInstanceId in", values, "processinstanceid");
			return (Criteria) this;
		}

		public Criteria andProcessinstanceidNotIn(List<String> values) {
			addCriterion("ProcessInstanceId not in", values, "processinstanceid");
			return (Criteria) this;
		}

		public Criteria andProcessinstanceidBetween(String value1, String value2) {
			addCriterion("ProcessInstanceId between", value1, value2, "processinstanceid");
			return (Criteria) this;
		}

		public Criteria andProcessinstanceidNotBetween(String value1, String value2) {
			addCriterion("ProcessInstanceId not between", value1, value2, "processinstanceid");
			return (Criteria) this;
		}

		public Criteria andDidIsNull() {
			addCriterion("DId is null");
			return (Criteria) this;
		}

		public Criteria andDidIsNotNull() {
			addCriterion("DId is not null");
			return (Criteria) this;
		}

		public Criteria andDidEqualTo(Integer value) {
			addCriterion("DId =", value, "did");
			return (Criteria) this;
		}

		public Criteria andDidNotEqualTo(Integer value) {
			addCriterion("DId <>", value, "did");
			return (Criteria) this;
		}

		public Criteria andDidGreaterThan(Integer value) {
			addCriterion("DId >", value, "did");
			return (Criteria) this;
		}

		public Criteria andDidGreaterThanOrEqualTo(Integer value) {
			addCriterion("DId >=", value, "did");
			return (Criteria) this;
		}

		public Criteria andDidLessThan(Integer value) {
			addCriterion("DId <", value, "did");
			return (Criteria) this;
		}

		public Criteria andDidLessThanOrEqualTo(Integer value) {
			addCriterion("DId <=", value, "did");
			return (Criteria) this;
		}

		public Criteria andDidIn(List<Integer> values) {
			addCriterion("DId in", values, "did");
			return (Criteria) this;
		}

		public Criteria andDidNotIn(List<Integer> values) {
			addCriterion("DId not in", values, "did");
			return (Criteria) this;
		}

		public Criteria andDidBetween(Integer value1, Integer value2) {
			addCriterion("DId between", value1, value2, "did");
			return (Criteria) this;
		}

		public Criteria andDidNotBetween(Integer value1, Integer value2) {
			addCriterion("DId not between", value1, value2, "did");
			return (Criteria) this;
		}

		public Criteria andUidIsNull() {
			addCriterion("UId is null");
			return (Criteria) this;
		}

		public Criteria andUidIsNotNull() {
			addCriterion("UId is not null");
			return (Criteria) this;
		}

		public Criteria andUidEqualTo(Integer value) {
			addCriterion("UId =", value, "uid");
			return (Criteria) this;
		}

		public Criteria andUidNotEqualTo(Integer value) {
			addCriterion("UId <>", value, "uid");
			return (Criteria) this;
		}

		public Criteria andUidGreaterThan(Integer value) {
			addCriterion("UId >", value, "uid");
			return (Criteria) this;
		}

		public Criteria andUidGreaterThanOrEqualTo(Integer value) {
			addCriterion("UId >=", value, "uid");
			return (Criteria) this;
		}

		public Criteria andUidLessThan(Integer value) {
			addCriterion("UId <", value, "uid");
			return (Criteria) this;
		}

		public Criteria andUidLessThanOrEqualTo(Integer value) {
			addCriterion("UId <=", value, "uid");
			return (Criteria) this;
		}

		public Criteria andUidIn(List<Integer> values) {
			addCriterion("UId in", values, "uid");
			return (Criteria) this;
		}

		public Criteria andUidNotIn(List<Integer> values) {
			addCriterion("UId not in", values, "uid");
			return (Criteria) this;
		}

		public Criteria andUidBetween(Integer value1, Integer value2) {
			addCriterion("UId between", value1, value2, "uid");
			return (Criteria) this;
		}

		public Criteria andUidNotBetween(Integer value1, Integer value2) {
			addCriterion("UId not between", value1, value2, "uid");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("Name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("Name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("Name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("Name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("Name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("Name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("Name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("Name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("Name like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("Name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("Name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("Name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("Name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("Name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andTelephoneIsNull() {
			addCriterion("Telephone is null");
			return (Criteria) this;
		}

		public Criteria andTelephoneIsNotNull() {
			addCriterion("Telephone is not null");
			return (Criteria) this;
		}

		public Criteria andTelephoneEqualTo(String value) {
			addCriterion("Telephone =", value, "telephone");
			return (Criteria) this;
		}

		public Criteria andTelephoneNotEqualTo(String value) {
			addCriterion("Telephone <>", value, "telephone");
			return (Criteria) this;
		}

		public Criteria andTelephoneGreaterThan(String value) {
			addCriterion("Telephone >", value, "telephone");
			return (Criteria) this;
		}

		public Criteria andTelephoneGreaterThanOrEqualTo(String value) {
			addCriterion("Telephone >=", value, "telephone");
			return (Criteria) this;
		}

		public Criteria andTelephoneLessThan(String value) {
			addCriterion("Telephone <", value, "telephone");
			return (Criteria) this;
		}

		public Criteria andTelephoneLessThanOrEqualTo(String value) {
			addCriterion("Telephone <=", value, "telephone");
			return (Criteria) this;
		}

		public Criteria andTelephoneLike(String value) {
			addCriterion("Telephone like", value, "telephone");
			return (Criteria) this;
		}

		public Criteria andTelephoneNotLike(String value) {
			addCriterion("Telephone not like", value, "telephone");
			return (Criteria) this;
		}

		public Criteria andTelephoneIn(List<String> values) {
			addCriterion("Telephone in", values, "telephone");
			return (Criteria) this;
		}

		public Criteria andTelephoneNotIn(List<String> values) {
			addCriterion("Telephone not in", values, "telephone");
			return (Criteria) this;
		}

		public Criteria andTelephoneBetween(String value1, String value2) {
			addCriterion("Telephone between", value1, value2, "telephone");
			return (Criteria) this;
		}

		public Criteria andTelephoneNotBetween(String value1, String value2) {
			addCriterion("Telephone not between", value1, value2, "telephone");
			return (Criteria) this;
		}

		public Criteria andRelativeIsNull() {
			addCriterion("Relative is null");
			return (Criteria) this;
		}

		public Criteria andRelativeIsNotNull() {
			addCriterion("Relative is not null");
			return (Criteria) this;
		}

		public Criteria andRelativeEqualTo(String value) {
			addCriterion("Relative =", value, "relative");
			return (Criteria) this;
		}

		public Criteria andRelativeNotEqualTo(String value) {
			addCriterion("Relative <>", value, "relative");
			return (Criteria) this;
		}

		public Criteria andRelativeGreaterThan(String value) {
			addCriterion("Relative >", value, "relative");
			return (Criteria) this;
		}

		public Criteria andRelativeGreaterThanOrEqualTo(String value) {
			addCriterion("Relative >=", value, "relative");
			return (Criteria) this;
		}

		public Criteria andRelativeLessThan(String value) {
			addCriterion("Relative <", value, "relative");
			return (Criteria) this;
		}

		public Criteria andRelativeLessThanOrEqualTo(String value) {
			addCriterion("Relative <=", value, "relative");
			return (Criteria) this;
		}

		public Criteria andRelativeLike(String value) {
			addCriterion("Relative like", value, "relative");
			return (Criteria) this;
		}

		public Criteria andRelativeNotLike(String value) {
			addCriterion("Relative not like", value, "relative");
			return (Criteria) this;
		}

		public Criteria andRelativeIn(List<String> values) {
			addCriterion("Relative in", values, "relative");
			return (Criteria) this;
		}

		public Criteria andRelativeNotIn(List<String> values) {
			addCriterion("Relative not in", values, "relative");
			return (Criteria) this;
		}

		public Criteria andRelativeBetween(String value1, String value2) {
			addCriterion("Relative between", value1, value2, "relative");
			return (Criteria) this;
		}

		public Criteria andRelativeNotBetween(String value1, String value2) {
			addCriterion("Relative not between", value1, value2, "relative");
			return (Criteria) this;
		}

		public Criteria andAgentIsNull() {
			addCriterion("Agent is null");
			return (Criteria) this;
		}

		public Criteria andAgentIsNotNull() {
			addCriterion("Agent is not null");
			return (Criteria) this;
		}

		public Criteria andAgentEqualTo(String value) {
			addCriterion("Agent =", value, "agent");
			return (Criteria) this;
		}

		public Criteria andAgentNotEqualTo(String value) {
			addCriterion("Agent <>", value, "agent");
			return (Criteria) this;
		}

		public Criteria andAgentGreaterThan(String value) {
			addCriterion("Agent >", value, "agent");
			return (Criteria) this;
		}

		public Criteria andAgentGreaterThanOrEqualTo(String value) {
			addCriterion("Agent >=", value, "agent");
			return (Criteria) this;
		}

		public Criteria andAgentLessThan(String value) {
			addCriterion("Agent <", value, "agent");
			return (Criteria) this;
		}

		public Criteria andAgentLessThanOrEqualTo(String value) {
			addCriterion("Agent <=", value, "agent");
			return (Criteria) this;
		}

		public Criteria andAgentLike(String value) {
			addCriterion("Agent like", value, "agent");
			return (Criteria) this;
		}

		public Criteria andAgentNotLike(String value) {
			addCriterion("Agent not like", value, "agent");
			return (Criteria) this;
		}

		public Criteria andAgentIn(List<String> values) {
			addCriterion("Agent in", values, "agent");
			return (Criteria) this;
		}

		public Criteria andAgentNotIn(List<String> values) {
			addCriterion("Agent not in", values, "agent");
			return (Criteria) this;
		}

		public Criteria andAgentBetween(String value1, String value2) {
			addCriterion("Agent between", value1, value2, "agent");
			return (Criteria) this;
		}

		public Criteria andAgentNotBetween(String value1, String value2) {
			addCriterion("Agent not between", value1, value2, "agent");
			return (Criteria) this;
		}

		public Criteria andTelephone2IsNull() {
			addCriterion("Telephone2 is null");
			return (Criteria) this;
		}

		public Criteria andTelephone2IsNotNull() {
			addCriterion("Telephone2 is not null");
			return (Criteria) this;
		}

		public Criteria andTelephone2EqualTo(String value) {
			addCriterion("Telephone2 =", value, "telephone2");
			return (Criteria) this;
		}

		public Criteria andTelephone2NotEqualTo(String value) {
			addCriterion("Telephone2 <>", value, "telephone2");
			return (Criteria) this;
		}

		public Criteria andTelephone2GreaterThan(String value) {
			addCriterion("Telephone2 >", value, "telephone2");
			return (Criteria) this;
		}

		public Criteria andTelephone2GreaterThanOrEqualTo(String value) {
			addCriterion("Telephone2 >=", value, "telephone2");
			return (Criteria) this;
		}

		public Criteria andTelephone2LessThan(String value) {
			addCriterion("Telephone2 <", value, "telephone2");
			return (Criteria) this;
		}

		public Criteria andTelephone2LessThanOrEqualTo(String value) {
			addCriterion("Telephone2 <=", value, "telephone2");
			return (Criteria) this;
		}

		public Criteria andTelephone2Like(String value) {
			addCriterion("Telephone2 like", value, "telephone2");
			return (Criteria) this;
		}

		public Criteria andTelephone2NotLike(String value) {
			addCriterion("Telephone2 not like", value, "telephone2");
			return (Criteria) this;
		}

		public Criteria andTelephone2In(List<String> values) {
			addCriterion("Telephone2 in", values, "telephone2");
			return (Criteria) this;
		}

		public Criteria andTelephone2NotIn(List<String> values) {
			addCriterion("Telephone2 not in", values, "telephone2");
			return (Criteria) this;
		}

		public Criteria andTelephone2Between(String value1, String value2) {
			addCriterion("Telephone2 between", value1, value2, "telephone2");
			return (Criteria) this;
		}

		public Criteria andTelephone2NotBetween(String value1, String value2) {
			addCriterion("Telephone2 not between", value1, value2, "telephone2");
			return (Criteria) this;
		}

		public Criteria andMoneyIsNull() {
			addCriterion("Money is null");
			return (Criteria) this;
		}

		public Criteria andMoneyIsNotNull() {
			addCriterion("Money is not null");
			return (Criteria) this;
		}

		public Criteria andMoneyEqualTo(Double value) {
			addCriterion("Money =", value, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyNotEqualTo(Double value) {
			addCriterion("Money <>", value, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyGreaterThan(Double value) {
			addCriterion("Money >", value, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyGreaterThanOrEqualTo(Double value) {
			addCriterion("Money >=", value, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyLessThan(Double value) {
			addCriterion("Money <", value, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyLessThanOrEqualTo(Double value) {
			addCriterion("Money <=", value, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyIn(List<Double> values) {
			addCriterion("Money in", values, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyNotIn(List<Double> values) {
			addCriterion("Money not in", values, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyBetween(Double value1, Double value2) {
			addCriterion("Money between", value1, value2, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyNotBetween(Double value1, Double value2) {
			addCriterion("Money not between", value1, value2, "money");
			return (Criteria) this;
		}

		public Criteria andSituationIsNull() {
			addCriterion("Situation is null");
			return (Criteria) this;
		}

		public Criteria andSituationIsNotNull() {
			addCriterion("Situation is not null");
			return (Criteria) this;
		}

		public Criteria andSituationEqualTo(String value) {
			addCriterion("Situation =", value, "situation");
			return (Criteria) this;
		}

		public Criteria andSituationNotEqualTo(String value) {
			addCriterion("Situation <>", value, "situation");
			return (Criteria) this;
		}

		public Criteria andSituationGreaterThan(String value) {
			addCriterion("Situation >", value, "situation");
			return (Criteria) this;
		}

		public Criteria andSituationGreaterThanOrEqualTo(String value) {
			addCriterion("Situation >=", value, "situation");
			return (Criteria) this;
		}

		public Criteria andSituationLessThan(String value) {
			addCriterion("Situation <", value, "situation");
			return (Criteria) this;
		}

		public Criteria andSituationLessThanOrEqualTo(String value) {
			addCriterion("Situation <=", value, "situation");
			return (Criteria) this;
		}

		public Criteria andSituationLike(String value) {
			addCriterion("Situation like", value, "situation");
			return (Criteria) this;
		}

		public Criteria andSituationNotLike(String value) {
			addCriterion("Situation not like", value, "situation");
			return (Criteria) this;
		}

		public Criteria andSituationIn(List<String> values) {
			addCriterion("Situation in", values, "situation");
			return (Criteria) this;
		}

		public Criteria andSituationNotIn(List<String> values) {
			addCriterion("Situation not in", values, "situation");
			return (Criteria) this;
		}

		public Criteria andSituationBetween(String value1, String value2) {
			addCriterion("Situation between", value1, value2, "situation");
			return (Criteria) this;
		}

		public Criteria andSituationNotBetween(String value1, String value2) {
			addCriterion("Situation not between", value1, value2, "situation");
			return (Criteria) this;
		}

		public Criteria andCreateuseridIsNull() {
			addCriterion("CreateUserId is null");
			return (Criteria) this;
		}

		public Criteria andCreateuseridIsNotNull() {
			addCriterion("CreateUserId is not null");
			return (Criteria) this;
		}

		public Criteria andCreateuseridEqualTo(Integer value) {
			addCriterion("CreateUserId =", value, "createuserid");
			return (Criteria) this;
		}

		public Criteria andCreateuseridNotEqualTo(Integer value) {
			addCriterion("CreateUserId <>", value, "createuserid");
			return (Criteria) this;
		}

		public Criteria andCreateuseridGreaterThan(Integer value) {
			addCriterion("CreateUserId >", value, "createuserid");
			return (Criteria) this;
		}

		public Criteria andCreateuseridGreaterThanOrEqualTo(Integer value) {
			addCriterion("CreateUserId >=", value, "createuserid");
			return (Criteria) this;
		}

		public Criteria andCreateuseridLessThan(Integer value) {
			addCriterion("CreateUserId <", value, "createuserid");
			return (Criteria) this;
		}

		public Criteria andCreateuseridLessThanOrEqualTo(Integer value) {
			addCriterion("CreateUserId <=", value, "createuserid");
			return (Criteria) this;
		}

		public Criteria andCreateuseridIn(List<Integer> values) {
			addCriterion("CreateUserId in", values, "createuserid");
			return (Criteria) this;
		}

		public Criteria andCreateuseridNotIn(List<Integer> values) {
			addCriterion("CreateUserId not in", values, "createuserid");
			return (Criteria) this;
		}

		public Criteria andCreateuseridBetween(Integer value1, Integer value2) {
			addCriterion("CreateUserId between", value1, value2, "createuserid");
			return (Criteria) this;
		}

		public Criteria andCreateuseridNotBetween(Integer value1, Integer value2) {
			addCriterion("CreateUserId not between", value1, value2, "createuserid");
			return (Criteria) this;
		}

		public Criteria andCreatetimeIsNull() {
			addCriterion("CreateTime is null");
			return (Criteria) this;
		}

		public Criteria andCreatetimeIsNotNull() {
			addCriterion("CreateTime is not null");
			return (Criteria) this;
		}

		public Criteria andCreatetimeEqualTo(Date value) {
			addCriterion("CreateTime =", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeNotEqualTo(Date value) {
			addCriterion("CreateTime <>", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeGreaterThan(Date value) {
			addCriterion("CreateTime >", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
			addCriterion("CreateTime >=", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeLessThan(Date value) {
			addCriterion("CreateTime <", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
			addCriterion("CreateTime <=", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeIn(List<Date> values) {
			addCriterion("CreateTime in", values, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeNotIn(List<Date> values) {
			addCriterion("CreateTime not in", values, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeBetween(Date value1, Date value2) {
			addCriterion("CreateTime between", value1, value2, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
			addCriterion("CreateTime not between", value1, value2, "createtime");
			return (Criteria) this;
		}

		public Criteria andIssuccessIsNull() {
			addCriterion("IsSuccess is null");
			return (Criteria) this;
		}

		public Criteria andIssuccessIsNotNull() {
			addCriterion("IsSuccess is not null");
			return (Criteria) this;
		}

		public Criteria andIssuccessEqualTo(Integer value) {
			addCriterion("IsSuccess =", value, "issuccess");
			return (Criteria) this;
		}

		public Criteria andIssuccessNotEqualTo(Integer value) {
			addCriterion("IsSuccess <>", value, "issuccess");
			return (Criteria) this;
		}

		public Criteria andIssuccessGreaterThan(Integer value) {
			addCriterion("IsSuccess >", value, "issuccess");
			return (Criteria) this;
		}

		public Criteria andIssuccessGreaterThanOrEqualTo(Integer value) {
			addCriterion("IsSuccess >=", value, "issuccess");
			return (Criteria) this;
		}

		public Criteria andIssuccessLessThan(Integer value) {
			addCriterion("IsSuccess <", value, "issuccess");
			return (Criteria) this;
		}

		public Criteria andIssuccessLessThanOrEqualTo(Integer value) {
			addCriterion("IsSuccess <=", value, "issuccess");
			return (Criteria) this;
		}

		public Criteria andIssuccessIn(List<Integer> values) {
			addCriterion("IsSuccess in", values, "issuccess");
			return (Criteria) this;
		}

		public Criteria andIssuccessNotIn(List<Integer> values) {
			addCriterion("IsSuccess not in", values, "issuccess");
			return (Criteria) this;
		}

		public Criteria andIssuccessBetween(Integer value1, Integer value2) {
			addCriterion("IsSuccess between", value1, value2, "issuccess");
			return (Criteria) this;
		}

		public Criteria andIssuccessNotBetween(Integer value1, Integer value2) {
			addCriterion("IsSuccess not between", value1, value2, "issuccess");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table project_activiti_apply
	 * @mbggenerated  Thu Aug 09 13:30:51 CST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table project_activiti_apply
     *
     * @mbggenerated do_not_delete_during_merge Fri Jun 29 14:25:54 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}