package com.partymasses.modules.dao.mybatis.entity;

public class TestUser extends TestUserKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_user.Score
     *
     * @mbggenerated Mon Apr 02 14:51:13 CST 2018
     */
    private Integer score;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_user.Score
     *
     * @return the value of test_user.Score
     *
     * @mbggenerated Mon Apr 02 14:51:13 CST 2018
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_user.Score
     *
     * @param score the value for test_user.Score
     *
     * @mbggenerated Mon Apr 02 14:51:13 CST 2018
     */
    public void setScore(Integer score) {
        this.score = score;
    }
}