package cn.caecc.erp.modules.dao.mybatis.entity;

import java.io.Serializable;

public class OfficesupplyGoodsRelationshipActivitiApply implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column officesupply_goods_relationship_activiti_apply.Id
     *
     * @mbggenerated Wed Aug 01 19:13:53 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column officesupply_goods_relationship_activiti_apply.OId
     *
     * @mbggenerated Wed Aug 01 19:13:53 CST 2018
     */
    private Integer oid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column officesupply_goods_relationship_activiti_apply.GCode
     *
     * @mbggenerated Wed Aug 01 19:13:53 CST 2018
     */
    private String gcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column officesupply_goods_relationship_activiti_apply.DId
     *
     * @mbggenerated Wed Aug 01 19:13:53 CST 2018
     */
    private Integer did;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column officesupply_goods_relationship_activiti_apply.ApplyCount
     *
     * @mbggenerated Wed Aug 01 19:13:53 CST 2018
     */
    private Integer applycount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column officesupply_goods_relationship_activiti_apply.CGId
     *
     * @mbggenerated Wed Aug 01 19:13:53 CST 2018
     */
    private Integer cgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column officesupply_goods_relationship_activiti_apply.Reason
     *
     * @mbggenerated Wed Aug 01 19:13:53 CST 2018
     */
    private String reason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table officesupply_goods_relationship_activiti_apply
     *
     * @mbggenerated Wed Aug 01 19:13:53 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column officesupply_goods_relationship_activiti_apply.Id
     *
     * @return the value of officesupply_goods_relationship_activiti_apply.Id
     *
     * @mbggenerated Wed Aug 01 19:13:53 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column officesupply_goods_relationship_activiti_apply.Id
     *
     * @param id the value for officesupply_goods_relationship_activiti_apply.Id
     *
     * @mbggenerated Wed Aug 01 19:13:53 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column officesupply_goods_relationship_activiti_apply.OId
     *
     * @return the value of officesupply_goods_relationship_activiti_apply.OId
     *
     * @mbggenerated Wed Aug 01 19:13:53 CST 2018
     */
    public Integer getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column officesupply_goods_relationship_activiti_apply.OId
     *
     * @param oid the value for officesupply_goods_relationship_activiti_apply.OId
     *
     * @mbggenerated Wed Aug 01 19:13:53 CST 2018
     */
    public void setOid(Integer oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column officesupply_goods_relationship_activiti_apply.GCode
     *
     * @return the value of officesupply_goods_relationship_activiti_apply.GCode
     *
     * @mbggenerated Wed Aug 01 19:13:53 CST 2018
     */
    public String getGcode() {
        return gcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column officesupply_goods_relationship_activiti_apply.GCode
     *
     * @param gcode the value for officesupply_goods_relationship_activiti_apply.GCode
     *
     * @mbggenerated Wed Aug 01 19:13:53 CST 2018
     */
    public void setGcode(String gcode) {
        this.gcode = gcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column officesupply_goods_relationship_activiti_apply.DId
     *
     * @return the value of officesupply_goods_relationship_activiti_apply.DId
     *
     * @mbggenerated Wed Aug 01 19:13:53 CST 2018
     */
    public Integer getDid() {
        return did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column officesupply_goods_relationship_activiti_apply.DId
     *
     * @param did the value for officesupply_goods_relationship_activiti_apply.DId
     *
     * @mbggenerated Wed Aug 01 19:13:53 CST 2018
     */
    public void setDid(Integer did) {
        this.did = did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column officesupply_goods_relationship_activiti_apply.ApplyCount
     *
     * @return the value of officesupply_goods_relationship_activiti_apply.ApplyCount
     *
     * @mbggenerated Wed Aug 01 19:13:53 CST 2018
     */
    public Integer getApplycount() {
        return applycount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column officesupply_goods_relationship_activiti_apply.ApplyCount
     *
     * @param applycount the value for officesupply_goods_relationship_activiti_apply.ApplyCount
     *
     * @mbggenerated Wed Aug 01 19:13:53 CST 2018
     */
    public void setApplycount(Integer applycount) {
        this.applycount = applycount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column officesupply_goods_relationship_activiti_apply.CGId
     *
     * @return the value of officesupply_goods_relationship_activiti_apply.CGId
     *
     * @mbggenerated Wed Aug 01 19:13:53 CST 2018
     */
    public Integer getCgid() {
        return cgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column officesupply_goods_relationship_activiti_apply.CGId
     *
     * @param cgid the value for officesupply_goods_relationship_activiti_apply.CGId
     *
     * @mbggenerated Wed Aug 01 19:13:53 CST 2018
     */
    public void setCgid(Integer cgid) {
        this.cgid = cgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column officesupply_goods_relationship_activiti_apply.Reason
     *
     * @return the value of officesupply_goods_relationship_activiti_apply.Reason
     *
     * @mbggenerated Wed Aug 01 19:13:53 CST 2018
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column officesupply_goods_relationship_activiti_apply.Reason
     *
     * @param reason the value for officesupply_goods_relationship_activiti_apply.Reason
     *
     * @mbggenerated Wed Aug 01 19:13:53 CST 2018
     */
    public void setReason(String reason) {
        this.reason = reason;
    }
}