package cn.caecc.erp.modules.dao.mybatis.mapper;

import cn.caecc.erp.modules.dao.mybatis.entity.WorkingSummary;
import cn.caecc.erp.modules.dao.mybatis.entity.WorkingSummaryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WorkingSummaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table working_summary
     *
     * @mbggenerated Mon Jul 30 09:17:36 CST 2018
     */
    int countByExample(WorkingSummaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table working_summary
     *
     * @mbggenerated Mon Jul 30 09:17:36 CST 2018
     */
    int deleteByExample(WorkingSummaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table working_summary
     *
     * @mbggenerated Mon Jul 30 09:17:36 CST 2018
     */
    int deleteByPrimaryKey(Integer workingsummaryid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table working_summary
     *
     * @mbggenerated Mon Jul 30 09:17:36 CST 2018
     */
    int insert(WorkingSummary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table working_summary
     *
     * @mbggenerated Mon Jul 30 09:17:36 CST 2018
     */
    int insertSelective(WorkingSummary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table working_summary
     *
     * @mbggenerated Mon Jul 30 09:17:36 CST 2018
     */
    List<WorkingSummary> selectByExample(WorkingSummaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table working_summary
     *
     * @mbggenerated Mon Jul 30 09:17:36 CST 2018
     */
    WorkingSummary selectByPrimaryKey(Integer workingsummaryid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table working_summary
     *
     * @mbggenerated Mon Jul 30 09:17:36 CST 2018
     */
    int updateByExampleSelective(@Param("record") WorkingSummary record, @Param("example") WorkingSummaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table working_summary
     *
     * @mbggenerated Mon Jul 30 09:17:36 CST 2018
     */
    int updateByExample(@Param("record") WorkingSummary record, @Param("example") WorkingSummaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table working_summary
     *
     * @mbggenerated Mon Jul 30 09:17:36 CST 2018
     */
    int updateByPrimaryKeySelective(WorkingSummary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table working_summary
     *
     * @mbggenerated Mon Jul 30 09:17:36 CST 2018
     */
    int updateByPrimaryKey(WorkingSummary record);
}