package com.partymasses.modules.dao.mybatis.entity;

public class UserNotice{
	
	public UserNotice(Integer userid, Integer noticeid, Integer status) {
		super();
		this.noticeid = noticeid;
		this.userid = userid;
		this.status = status;
	}
	
	public UserNotice() {
		super();
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_notice.NoticeId
     *
     * @mbggenerated Wed Mar 28 08:54:38 CST 2018
     */
    private Integer noticeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_notice.UserId
     *
     * @mbggenerated Wed Mar 28 08:54:38 CST 2018
     */
    private Integer userid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_notice.NoticeId
     *
     * @return the value of user_notice.NoticeId
     *
     * @mbggenerated Wed Mar 28 08:54:38 CST 2018
     */
    public Integer getNoticeid() {
        return noticeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_notice.NoticeId
     *
     * @param noticeid the value for user_notice.NoticeId
     *
     * @mbggenerated Wed Mar 28 08:54:38 CST 2018
     */
    public void setNoticeid(Integer noticeid) {
        this.noticeid = noticeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_notice.UserId
     *
     * @return the value of user_notice.UserId
     *
     * @mbggenerated Wed Mar 28 08:54:38 CST 2018
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_notice.UserId
     *
     * @param userid the value for user_notice.UserId
     *
     * @mbggenerated Wed Mar 28 08:54:38 CST 2018
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_notice.Status
     *
     * @mbggenerated Wed Mar 28 08:54:38 CST 2018
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_notice.Status
     *
     * @return the value of user_notice.Status
     *
     * @mbggenerated Wed Mar 28 08:54:38 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_notice.Status
     *
     * @param status the value for user_notice.Status
     *
     * @mbggenerated Wed Mar 28 08:54:38 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}